### ISSUE TITLE
NoSuchMethodError with Spring Boot 2.1.0.M4

### ISSUE THREAD

**Issue by anderius** [ulisesbocchio/jasypt-spring-boot#102]
Spring Boot 2.1 changed the return type of `org.springframework.boot.convert.ApplicationConversionService#getSharedInstance` from `ConversionService` to `ApplicationConversionService`.

Somehow this breaks jasypt-spring-boot:

`Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'lazyEncryptablePropertyFilter' defined in class path resource [com/ulisesbocchio/jasyptspringboot/configuration/EncryptablePropertyResolverConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.ulisesbocchio.jasyptspringboot.EncryptablePropertyFilter]: Factory method 'encryptablePropertyFilter' threw exception; nested exception is java.lang.NoSuchMethodError: org.springframework.boot.convert.ApplicationConversionService.getSharedInstance()Lorg/springframework/core/convert/ConversionService;`

I know too little of byte code, but I guess the error is because the library was compiled against Spring Boot 2.0.x, and that method signature change is somehow not compatible?

**Comment by jpmsilva** [comment]
Hello

I created an [issue](/spring-projects/spring-boot/issues/14938) with the Spring Boot project, hoping that they can shed some light if this breaking change in the `ApplicationConversionService.getSharedInstance()` is really needed.

I'm hoping that this may still be reversed, as releasing the jasypt spring boot project compiled against Spring Boot 2.1, if this breaking change is not reversed, will make it backward incompatible with Spring Boot 2.0, 1,5 and 1.4.

**Comment by ulisesbocchio** [comment]
tested on 2.1.0, thanks @philwebb
