### ISSUE TITLE
help...encryptor automatic configuration

### ISSUE THREAD

**Issue by dcampello** [ulisesbocchio/jasypt-spring-boot#108]
is it possible to use the same encryptor configuration that automatically detects and decrypts data from the .properties file to decrypt an encrypted variable elsewhere in the application? How do I recover this encryptor already configured to reuse in the application? I'm using with spring and the @SpringBootApplication and @EnableAutoConfiguration annotations

**Comment by ulisesbocchio** [comment]
yes, the default bean name is: jasyptStringEncryptor but you can also inject it by type: StringEncryptor.
Here's the doc section: https://github.com/ulisesbocchio/jasypt-spring-boot#use-you-own-custom-encryptor
