### ISSUE TITLE
Private key instead of String password?

### ISSUE THREAD

**Issue by sddakoty** [ulisesbocchio/jasypt-spring-boot#110]
Would it be possible to use a private key as "password" for the property encryption?
Probably there is no chance in getting that feature into native jasypt, as last version update was in 2014.

But maybe you could add such a feature in your spring wrapper?

**Comment by ulisesbocchio** [comment]
done! enjoy: https://github.com/ulisesbocchio/jasypt-spring-boot#asymmetric-encryption
