### ISSUE TITLE
Incorrect client defined property resolver should cause failure

### ISSUE THREAD

**Issue by stevejb71** [ulisesbocchio/jasypt-spring-boot#114]
If a jasypt.encryptor.property.resolver-bean is specified, but the bean is not found, Spring jasypt falls back to the default property descriptor with an info log (in DefaultLazyPropertyResolver).

I think a failure is a better response, as the bean has been explicitly specified by the client code.

**Comment by ulisesbocchio** [comment]
I hear ya, lemme se what I can do...

**Comment by stevejb71** [comment]
Great, thank you!

**Comment by ulisesbocchio** [comment]
will be in next release
