### ISSUE TITLE
Relaxed binding  is not support

### ISSUE THREAD

**Issue by Yuhuiyang-Dev** [ulisesbocchio/jasypt-spring-boot#115]
Currently only support read properties on 'jasypt.encryptor.password', Relaxed binding read is not supported  . related connection  https://docs.spring.io/spring-boot/docs/1.5.19.RELEASE/reference/htmlsingle/#boot-features-external-config-relaxed-binding

**Comment by ulisesbocchio** [comment]
It works partially, for instance you can set `JASYPT_ENCRYPTOR_PASSWORD`or `JASYPT_ENCRYPTOR_KEYOBTENTIONITERATIONS` but not `JASYPT_ENCRYPTOR_KEY_OBTENTION_ITERATIONS` but I'll get those fixed

**Comment by ulisesbocchio** [comment]
fixed, will be out next release, thanks for reporting!
