### ISSUE TITLE
Reset/Reload jasypt.encryptor.password at runtime

### ISSUE THREAD

**Issue by Savers80** [ulisesbocchio/jasypt-spring-boot#118]
Hi,
I use jasypt-spring-boot-starter and configured Web Application with @SpringBootApplication
to read Environment property;
Into Login action Controller the webApp ask the password of jasypt and i use it to set System.setProperty("jasypt.encryptor.password", jasyptPassword);

If the password is correct all work correctly,
the problem is when the password is not correct (with the subsequent tentative to set the correct password) the properties are not decripted:
com.ulisesbocchio.jasyptspringboot.exception.DecryptionException: Decryption of Properties failed,  make sure encryption/decryption passwords match; 
how a can force to reload the correct password without restart the application ?

Very thanks, Saverio

**Comment by ulisesbocchio** [comment]
you can try something like this: https://andressanchezblog.wordpress.com/2016/09/15/refresh-scope-in-spring-cloud/
using the `@RefreshScope` annotation on a custom `stringEncryptor` bean
