### ISSUE TITLE
Update to Spring Boot 2.1.2 Release

### ISSUE THREAD

**Issue by melloware** [ulisesbocchio/jasypt-spring-boot#119]
Please update to Spring Boot 2.1.2.

Also any word on a release any time soon?

**Comment by ulisesbocchio** [comment]
Yes, sorry, will release shortly!

**Comment by ulisesbocchio** [comment]
done! Thanks for your contributions @melloware!
Checkout the new [asymmetric encryption](https://github.com/ulisesbocchio/jasypt-spring-boot#asymmetric-encryption) feature

**Comment by melloware** [comment]
Nice work and thanks for the release!  My clients will be happy now I can move to higher encryption levels.
