### ISSUE TITLE
How to encrypt string using jascypt cli

### ISSUE THREAD

**Issue by chriswhite199** [ulisesbocchio/jasypt-spring-boot#121]
Is there any advice on how to encrypt a string from the CLI?

I assumed that i could just use the same Class that jasypt's bin/encrypt.sh uses, but that yields garbage when decrypted inside a Spring Boot application;

I added a gradle task as follows to assist:

```groovy
task encrypt(type: JavaExec) {
    classpath = sourceSets.main.runtimeClasspath
    main = 'org.jasypt.intf.cli.JasyptPBEStringEncryptionCLI'
    args = [ 'input=' + input, 'password=' + password ]
}
```

And invoked by:

```
./gradlew :encrypt -Pinput=test -Ppassword=password123
```

But the defaults used by DefaultLazyEncryptor inside spring as output in the logs uses a saltGenerator (which can be configured from the CLI args) and an ivGenerator (for which there is no way to configure via CLI args).

So any encrypted value i use generated by the encrypt task will not correctly decrypt (it doesn't error, its just the decrypted string is binary vs the unencrypted string). I could of course configure spring to use the same defaults, but i'd like to utilize the improvements in jasypt 1.9.4 for better encryption etc

I didn't see any advice for generating encrypted strings in the main README.md - any advice?

**Comment by brunomendola** [comment]
I can confirm this issue, starting from version 2.1.1.

I had to revert to version 2.1.0 to make the CLI work again.

**Comment by chriswhite199** [comment]
In the end i had to create a Helper class to call from groovy, instead of the Jasypt CLI class:

Badly Copy&Pasted from another machine, so apologies for any typos :

```java
public static void main(final String[] args) {
  final StandardEnvironment env = new StandardEnvironment();
  final DefaultLazyEncryptor enc = new DefaultLazyEncryptor(env);

  System.out.printf("Encrypted:\t%s%n", enc.encrypt(args[0]));
}
```

**Comment by ulisesbocchio** [comment]
That's good. The library doesn't provide a CLI interface. I'm all years as to what a CLI would look like and contributions are welcome in this area.

**Comment by ulisesbocchio** [comment]
we're going back to jasypt-1.9.3 in next release
