### ISSUE TITLE
Decrypted property is showing with funny characters.

### ISSUE THREAD

**Issue by yerko76** [ulisesbocchio/jasypt-spring-boot#123]
Hi, when my app resolves encrypted property those properties are showing funny characters and I'm no able to provide the right credentials

My property is = �U�|�aװ�ı����QY��F0ldo

 compile'com.github.ulisesbocchio:jasypt-spring-boot-starter:2.1.1'
'org.springframework.boot' version '2.1.3.RELEASE'

hello: ENC(JKISZ6XdI94/+ztspLLRgIc+hXjiZTlQ/VuzBR3jYbqmMRE6IGeYUw==)

jasypt:
  encryptor:
    password: some test

**Comment by TheMercuryBeat** [comment]
Hi there,

I'm migrating from Spring Boot 1 to Spring Boot 2. When the property is decrypted in Spring Boot 1 works. But now I don't know what happens, in Spring boot 2 when the app gets the property from database and decrypt it, the value is �d�x��X�W����

Could you help me?

Thanks

**Comment by bedla** [comment]
It seems that Jasypt CLI default `ivGeneratorClassname` is `null` (and cannot be recofigured), result of this is that default value equals to `org.jasypt.salt.RandomIVGenerator` (not Noop IV generator), compare [boot-jasypt implementation](https://github.com/ulisesbocchio/jasypt-spring-boot/blob/jasypt-spring-boot-parent-2.1.1/jasypt-spring-boot/src/main/java/com/ulisesbocchio/jasyptspringboot/encryptor/DefaultLazyEncryptor.java#L72) with [jasypt implementation](https://github.com/melloware/jasypt/blob/1.9.4/src/main/java/org/jasypt/encryption/pbe/StandardPBEByteEncryptor.java#L593).

I have solved this by setting `jasypt.encryptor.ivGeneratorClassname` property to `org.jasypt.salt.RandomIVGenerator` to be compliant with Jasypt CLI implementation and allow Ops to generate their password using CLI.

**Comment by ulisesbocchio** [comment]
IV generator was rolled back to original Jasypt, this should be fixed in next release
