### ISSUE TITLE
In the integration of spring-cloud-starter-bus-amqp, spring-cloud-config-server request /bus/refresh error

### ISSUE THREAD

**Issue by yangkebiao** [ulisesbocchio/jasypt-spring-boot#125]
the log shows that the parameter is not decrypted, resulting in an exception，version：jasypt-spring-boot-starter:2.0.0
log error info：java.net.UnknownHostException: ENC{tRq91isva....

**Comment by madhu1707** [comment]
@yangkebiao : facing the same issue with spring cloud consul's refresh. Were you able to fix the issue?

**Comment by lp0601** [comment]
Is the issue fixed?

**Comment by ulisesbocchio** [comment]
haven't fixed this... I'm gonna need a sample app where the problem shows... can you provide?

**Comment by ulisesbocchio** [comment]
closing due to no response
