### ISSUE TITLE
Can jasypt-spring-boot support some AES algorithm ？

### ISSUE THREAD

**Issue by zhangzhaoyu** [ulisesbocchio/jasypt-spring-boot#130]
Hi, Can jasypt-spring-boot support some AES algorithm ？how can I set jasypt.encryptor.algorithm?

**Comment by melloware** [comment]
Yes using 2.1.1 you can use PBEWITHHMACSHA512ANDAES_256


jasypt.encryptor.password | True | -
-- | -- | --
jasypt.encryptor.algorithm | False | PBEWITHHMACSHA512ANDAES_256
jasypt.encryptor.keyObtentionIterations | False | 1000
jasypt.encryptor.poolSize | False | 1
jasypt.encryptor.providerName | False | SunJCE
jasypt.encryptor.providerClassName | False | null
jasypt.encryptor.saltGeneratorClassname | False | org.jasypt.salt.RandomSaltGenerator
jasypt.encryptor.ivGeneratorClassname | False | org.jasypt.salt.RandomIVGenerator
jasypt.encryptor.stringOutputType | False | base64
jasypt.encryptor.proxyPropertySources | False | false

**Comment by ulisesbocchio** [comment]
thanks @melloware
