### ISSUE TITLE
Getting-started documentation in README

### ISSUE THREAD

**Issue by chrylis** [ulisesbocchio/jasypt-spring-boot#132]
The main README suggests inserting property entries like this:

```
jasypt.encryptor.password=${JASYPT_ENCRYPTOR_PASSWORD:}
```

However, Spring Boot's property binding already handles this internally, and these entries appear to be redundant.

**Comment by ulisesbocchio** [comment]
I am aware, and although that particular example seems redundant, it helps understand that you can map it to any other ENV variable you desire:
```properties
jasypt.encryptor.password=${SOME_OTHER_VARIABLE_THAT_HOLDS_MY_PASSWORD:}
```
