### ISSUE TITLE
jasypt encryption in bootstrap.yml

### ISSUE THREAD

**Issue by gitmykeul** [ulisesbocchio/jasypt-spring-boot#135]
Hi,
I have jasypt-spring-boot-starter in my dependencies.
I have the --jasypt.encryptor.password as a program argument.
I am also using the StandardEncryptableEnvironment:

```
new SpringApplicationBuilder()
                .environment(new StandardEncryptableEnvironment())
``` 
Encrypted properties in application.yml work fine.
However encrypted properties do not work in bootstrap.yml
(I want to encrypt password to connect to config server).

Is it possible to use encryption at the bootstrap level? Am I missing something?

Thanks.

**Comment by ulisesbocchio** [comment]
As far as I know bootstrap.xml loads it’s own application context not shared with your application context. There might be a way though through a similar mechanism as spring.factories where you can tap in that context. I don’t know from the top of my head how to do it.
I’ll dig around and see if I can give you more hints

**Comment by gitmykeul** [comment]
Thanks!

**Comment by ulisesbocchio** [comment]
this should work with the starter jar and property:
```properties
spring.cloud.bootstrap.enabled=true
```
