### ISSUE TITLE
Library can breaks jdk1.7 projects

### ISSUE THREAD

**Issue by gunnarr-u** [ulisesbocchio/jasypt-spring-boot#14]
Throws java.lang.UnsuppotedClassVersionError

**Comment by ulisesbocchio** [comment]
There was a previous issue about this. This Library is written and compiled for Java 8. If you're using Spring Boot there's no reason for being on Java 7 so let me ask you, why are you running on Java 7?

**Comment by curiousElf** [comment]
I have the same issue. And as for the reason - client constraints. For a bunch of unsubstantiated reasons, they do not want to upgrade to java 8 as of now.

**Comment by ulisesbocchio** [comment]
Alright, I'll see if I can back port it in a different branch with a qualifier for Java7. Shouldn't take too long

**Comment by ulisesbocchio** [comment]
version 1.4-java7 should be in central soon

**Comment by curiousElf** [comment]
Thanks!

**Comment by gunnarr-u** [comment]
Thanks
