### ISSUE TITLE
Can not decrypt default expose parameter spring boot yaml

### ISSUE THREAD

**Issue by thapld** [ulisesbocchio/jasypt-spring-boot#143]
I have a config:
`secret:
  username: ${ABC:ENC(r3tFbUiZhdnGmjEUvD1p6Q==)}`

And jasypt return **ENC(r3tFbUiZhdnGmjEUvD1p6Q==)** when I get property
Can you help me? Thank you so much.

**Comment by mwiede** [comment]
I faced the same issue and found #75 which describes the same. See the workaround there.

**Comment by ulisesbocchio** [comment]
will be fixed in next release
