### ISSUE TITLE
Melloware Jasypt 1.9.4 encrypted outputs fails but Jasypt 1.9.3 works

### ISSUE THREAD

**Issue by pgi-jsanchez** [ulisesbocchio/jasypt-spring-boot#146]
Greetings.

I did a test with both versions and using the same spring boot project and jaspypt-spring boot version 2.1.1. I used PBEWITHSHA1ANDRC2_40 algorithm it's one of them that works in both jasypt cli versions. It turns out, that for some reason the encrypted output from the Melloware cli does not work properly with this project and gives throws a DecryptionException: Decryption of Properties failed,  make sure encryption/decryption passwords match.

There is any reason for this bug?

**Comment by melloware** [comment]
This PR https://github.com/ulisesbocchio/jasypt-spring-boot/pull/151 will fix it by updating to Jasypt 1.9.3.  

Mine was a temporary fix to get PBEWITHHMACSHA512ANDAES_256 working and provide it.  Not all new encryption types I believe were testing.

**Comment by ulisesbocchio** [comment]
we're going back to jasypt 1.9.3 in next release

**Comment by pgi-jsanchez** [comment]
Following this thread, I tried to encrypt with those parameters and here is the result.

sh encrypt.sh saltGeneratorClassName=org.jasypt.salt.RandomIVGenerator algorithm=PBEWITHHMACSHA512ANDAES_256 input=test password=testing

----ENVIRONMENT-----------------

Runtime: Oracle Corporation OpenJDK 64-Bit Server VM 25.171-b10 



----ARGUMENTS-------------------

input: test
algorithm: PBEWITHHMACSHA512ANDAES_256
password: testing
saltGeneratorClassName: org.jasypt.salt.RandomIVGenerator



----ERROR-----------------------

java.lang.ClassCastException: org.jasypt.salt.RandomIVGenerator cannot be cast to org.jasypt.salt.SaltGenerator

Even if this project rollsback to jasypt 1.9.3 in the future, might be important when maybe your jasypt fork works better with spring, otherwise, there might not be improvement with newer algorithms like you propose on your fork.

I hope it helps to debug this.

> See this answer: #145
> 
> Also can you paste your CLI command here? Are you sure you didn't forget to match up the IvGenerator in the CLI with the one in your properties file.
> 
> > The property jasypt.encryptor.ivGeneratorClassname defaults to NoOpIVGenerator for backwards compatibility. However, if you would like to use the newer algorithms in Java 8+ (e.g. PBEWITHHMACSHA512ANDAES_256) you must set this value to org.jasypt.salt.RandomIVGenerator.

**Comment by melloware** [comment]
Change it to just..

```
sh encrypt.sh algorithm=PBEWITHHMACSHA512ANDAES_256 input=test password=testing
```
