### ISSUE TITLE
@Autowired is not injecting default StringEncryptor in version 2.*.*

### ISSUE THREAD

**Issue by pragmaticway** [ulisesbocchio/jasypt-spring-boot#147]
When I'm trying to inject default StringEncryptor instance, it works only for versions prior 2.*.

Here is the dependency/code:
```
<dependency>
        <groupId>com.github.ulisesbocchio</groupId>
        <artifactId>jasypt-spring-boot-starter</artifactId>
        <version>1.18</version>
</dependency>
```
Config fragment:
```
jasypt:
  encryptor:
    password: ABCDXYZ1234!@#$
```

Code:
```
public class TestBootTest {
    @Autowired
    StringEncryptor stringEncryptor;//Automatic Injection 

    @Test
    public void test() {
        System.out.println(stringEncryptor.encrypt("123456"));
    }
}
```

When I upgrade to version 2.1.1:
```
<dependency>
        <groupId>com.github.ulisesbocchio</groupId>
        <artifactId>jasypt-spring-boot-starter</artifactId>
        <version>2.1.1</version>
</dependency>
```

Getting error:

> org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.jasypt.encryption.StringEncryptor' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}

Why it doesn't work?

**Comment by ulisesbocchio** [comment]
Check this out: https://github.com/ulisesbocchio/jasypt-spring-boot-samples/blob/master/jasypt-spring-boot-demo-simple/src/test/java/demo/SimpleDemoApplicationTest.java
