### ISSUE TITLE
Not possible: spring.cloud.config.password=${SPRING_CLOUD_CONFIG_PASS:ENC(xXxXxXx)}

### ISSUE THREAD

**Issue by patpatpat123** [ulisesbocchio/jasypt-spring-boot#148]
Hello Jasypt Team,

First of all, a big thank you for this very cool project.
I am a bit confused by this issue:

If I do 
spring.cloud.config.password=myPasswordInClear
It is obviously working.

If I do 
spring.cloud.config.password=ENC(xXxXxXx)
It is obviously working, thanks to your cool project.

If I do 
spring.cloud.config.password=${SPRING_CLOUD_CONFIG_PASS:myPasswordInClear}
It is also working, which also gives me the flexibility for other environments to override with SPRING_CLOUD_CONFIG_PASS

However, if I do: 
spring.cloud.config.password=${SPRING_CLOUD_CONFIG_PASS:ENC(xXxXxXx)}
This is not working anymore.

May I kindly ask about the status on this issue, and how to solve it?
Thank you for your time.

**Comment by ulisesbocchio** [comment]
will be fixed in the next release

**Comment by patpatpat123** [comment]
Hello,

Thank you for your comment.
Looking forward to the next  (2.1.3?) version.

**Comment by ulisesbocchio** [comment]
2.1.2 is the new release. It's already out

**Comment by patpatpat123** [comment]
Hello,

Confirm, tested and working with 2.1.2/
Much appreciated. good day!
