### ISSUE TITLE
springboot 2.2.0.M5 invalid

### ISSUE THREAD

**Issue by 120011676** [ulisesbocchio/jasypt-spring-boot#150]
springboot 2.2.0.M5 invalid

jasypt:
  encryptor:
    private-key-format: pem
    private-key-location: secret/private.pem

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2019-09-03 18:34:31.272 ERROR 70244 --- [  restartedMain] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

Failed to bind properties under 'spring.datasource.password' to java.lang.String:

    Reason: either 'jasypt.encryptor.password' or one of ['jasypt.encryptor.privateKeyString', 'jasypt.encryptor.privateKeyLocation'] must be provided for Password-based or Asymmetric encryption

Action:

Update your application's configuration

Disconnected from the target VM, address: '127.0.0.1:50297', transport: 'socket'

Process finished with exit code 0

**Comment by ulisesbocchio** [comment]
We'll add support soon
