### ISSUE TITLE
jasypt-spring-boot-starter randomly prevents Spring Boot app from starting

### ISSUE THREAD

**Issue by j0rdanit0** [ulisesbocchio/jasypt-spring-boot#160]
After adding the jasypt-spring-boot-starter maven dependency (version 2.1.2), approximately once out of every 8 starts of my Spring Boot app fails. No error logs are printed, it simply never starts up.

This behavior has never happened before adding the jasypt dependency, and now happens regularly (approximately 1/8 startups).

When comparing the logs of a successful start vs. those of a failed start, I noticed that it always stops during the "`Encryptor config not found...using default value`" section. I found these logs in the `DefaultLazyEncryptor` class, and are written out as part of the `createPBEDefault(Environment e)` method. Please see these various examples; they each fail at a different point:
[logs-with-failure.txt](https://github.com/ulisesbocchio/jasypt-spring-boot/files/3730403/logs-with-failure.txt)
[logs-with-failure2.txt](https://github.com/ulisesbocchio/jasypt-spring-boot/files/3730410/logs-with-failure2.txt)
[logs-with-failure3.txt](https://github.com/ulisesbocchio/jasypt-spring-boot/files/3730411/logs-with-failure3.txt)
Here is an example of successful logs:
[logs-with-success.txt](https://github.com/ulisesbocchio/jasypt-spring-boot/files/3730413/logs-with-success.txt)

What I believe is happening is something is causing an exception to be thrown (the random nature of this issue seems to indicate to me that it is some sort of race condition), which goes uncaught. `createPBEDefault(Environment e)` is invoked as part of an `Optional `chain inside of `createDefault(Environment e)`, which has no error handling, and is invoked as part of a lambda in the `DefaultLazyEncryptor(final Environment e, final String customEncryptorBeanName, boolean isCustom, final BeanFactory bf)` constructor, which also has no error handling. I believe it is at this point that the program control flow is severed, and the remaining startup tasks are left uncompleted and the app fails to start.

I would love to be able to use jasypt for my project. Please let me know if I can help in any way. Thank you.

**Comment by mpaetzold** [comment]
I experience almost the same. https://github.com/ulisesbocchio/jasypt-spring-boot/issues/131#issuecomment-548869404 might fix the issue.

**Comment by ulisesbocchio** [comment]
There's PR to fix this issue. I'll merge/release soon

**Comment by ulisesbocchio** [comment]
fixed in 3.0.0
