### ISSUE TITLE
spring2.2 不兼容jasypt-spring-boot-starter 2.1.1

### ISSUE THREAD

**Issue by zuoqi1993125** [ulisesbocchio/jasypt-spring-boot#162]
![image](https://user-images.githubusercontent.com/33927898/67539401-9acc5600-f714-11e9-9822-9a569ba072ca.png)

**Comment by ulisesbocchio** [comment]
I'm not an mybatis kind of guy. can you provide a code sample to investigate?

**Comment by duanhairuo** [comment]
this not jasypt problem, this zhe mybatis's !!!

**Comment by ulisesbocchio** [comment]
thanks @zuoqi1993125, closing
