### ISSUE TITLE
Properties in bootstrap.yml are ignored

### ISSUE THREAD

**Issue by bjornharvold** [ulisesbocchio/jasypt-spring-boot#163]
Thanks for a great Spring Boot starter. I tried this out for the first time today. Works great expect bootstrap.yml properties are completely ignore. Spring Boot app will fail if some code relies on properties in bootstrap.yml. This is where I used to inject the encryption key as it's the first file read by Spring Boot.

Cheers,
Bjorn

**Comment by ulisesbocchio** [comment]
bootstrap.yml loads in a completely different ApplicationContext. I'm not sure you can share properties between bootstrap.yml and the application. I'd have to dig a bit

**Comment by ulisesbocchio** [comment]
This should be good in 3.0.0
For a full working example take a look at: https://github.com/ulisesbocchio/jasypt-spring-boot-samples/tree/master/jasypt-spring-boot-demo-cloud-config
