### ISSUE TITLE
java.lang.NoClassDefFoundError: org/springframework/boot/context/properties/bind/PlaceholdersResolver

### ISSUE THREAD

**Issue by beeuday** [ulisesbocchio/jasypt-spring-boot#165]
I need to use the stronger algorithms for encryption and decryption. So I started using the latest version of Jasypt-Spring-boot 2.1.2 with spring boot 1.5.3 version application.

I am getting the following exception while starting the application 

o.s.boot.SpringApplication - Application startup failed
java.lang.NoClassDefFoundError: org/springframework/boot/context/properties/bind/PlaceholdersResolver
at java.lang.Class.getDeclaredMethods0(Native Method)
at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)

Can you please help me how to fix this issue ?

**Comment by rupert-madden-abbott** [comment]
I'm not the owner but as far as I can see, version 2+ of jasypt-spring-boot-starter have hardcoded dependencies on classes that only exist in version 2+ of Spring Boot.

Therefore, it would seem that if you want to use version 2+ of jasypt-spring-boot-starter, you must also using version 2+ of Spring Boot.

It may be that if you want to use earlier versions of Spring Boot, then you must also use an earlier version of this starter.

**Comment by ulisesbocchio** [comment]
thanks @rupert-madden-abbott, that sounds about right. I'll update the compatibility section in the readme

**Comment by ulisesbocchio** [comment]
Updated in release 3.0.0
