### ISSUE TITLE
Use a stronger default PBE algorithm in Spring Boot 2+

### ISSUE THREAD

**Issue by rupert-madden-abbott** [ulisesbocchio/jasypt-spring-boot#167]
The current default PBE algorithm is PBEWithMD5AndDES.

As far as I can see, this algorithm is not really secure but, because it is the default, many people are likely to use it.

I know this algorithm is the default in Jasypt itself, which requires backwards compatibility to Java 6.

However, Spring Boot 2 requires Java 8 so would it be possible to set a stronger default algorithm for the Spring Boot 2+ releases e.g. PBEWITHHMACSHA512ANDAES_256? This would also mean defaulting jasypt.encryptor.ivGeneratorClassname to org.jasypt.iv.RandomIvGenerator.

Currently, my organisation uses this for encryption/decryption in 100+ applications as well deployment tooling and not having to set the algorithm to something stronger everywhere would be helpful!

I'm happy to a raise a PR if you are happy to accept this feature request. No worries if not!

**Comment by ulisesbocchio** [comment]
Happy to take a PR with the change... thanks for the feedback and using the library :)
