### ISSUE TITLE
Can i use PasswordEnvName this properties.

### ISSUE THREAD

**Issue by JF950908** [ulisesbocchio/jasypt-spring-boot#169]
Otherwise, password has been exposed. How to encrypt safely？

**Comment by ulisesbocchio** [comment]
A bit of a cryptic message. Can you explain a bit more?
If I get this correctly, the recommended way is to put your decryption password in the ENV of the machine that's gonna do the decryption and nowhere else. The with Spring you can consume the ENV variable and feed it to the plugin

**Comment by ulisesbocchio** [comment]
closing due to no response
