### ISSUE TITLE
 Configuration properties cannot be refreshed dynamically when using this 

### ISSUE THREAD

**Issue by rwbykit** [ulisesbocchio/jasypt-spring-boot#172]
When I used Apollo as the config center, I changed the value of the attribute dynamically through the configuration center, but it didn't work. I checked the source code and found cache when after first acquired.  If I want to change the property value dynamically, what should I do ？

**Comment by ulisesbocchio** [comment]
I'm not familiar with Apollo as a config server. Can you provide:
*  An example
* Your jasypt-spring-boot configuration
And make sure that:
* Apollo Server is invoking the `/refresh` endpoint on your application (Or you're calling it)
* Your configuration-accessing beans are annotated with `@RefreshScope`

`jasypt-spring-boot` adds this event listener when using `@EnableEncryptableProperties` or `@EncryptablePropertySource`:
```java
@Order(Ordered.HIGHEST_PRECEDENCE)
@Slf4j
public class RefreshScopeRefreshedEventListener implements ApplicationListener<ApplicationEvent> {

    public static final String REFRESHED_EVENT_CLASS = "org.springframework.cloud.context.scope.refresh.RefreshScopeRefreshedEvent";
    private final ConfigurableEnvironment environment;

    public RefreshScopeRefreshedEventListener(ConfigurableEnvironment environment) {
        this.environment = environment;
    }

    @Override
    @SneakyThrows
    public void onApplicationEvent(ApplicationEvent event) {
        ClassLoader classLoader = this.getClass().getClassLoader();
        boolean refreshedPresent = ClassUtils.isPresent(REFRESHED_EVENT_CLASS, classLoader);
        if (refreshedPresent) {
            Class<?> refreshedClass = ClassUtils.forName(REFRESHED_EVENT_CLASS, classLoader);
            if (ClassUtils.isAssignableValue(refreshedClass, event)) {
                log.info("Refreshing cached encryptable property sources");
                refreshCachedProperties();
            }
        }
    }

    private void refreshCachedProperties() {
        PropertySources propertySources = environment.getPropertySources();
        propertySources.forEach(this::refreshPropertySource);
    }

    private void refreshPropertySource(PropertySource<?> propertySource) {
        if (propertySource instanceof CompositePropertySource) {
            CompositePropertySource cps = (CompositePropertySource) propertySource;
            cps.getPropertySources().forEach(this::refreshPropertySource);
        } else if (propertySource instanceof EncryptablePropertySource){
            EncryptablePropertySource eps = (EncryptablePropertySource) propertySource;
            eps.refresh();
        }
    }
}
```

**Comment by rwbykit** [comment]
A simple springCloud application using Apollo config center 
pom.xml
```
 <dependency>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-web</artifactId>
	<version>2.2.1.RELEASE</version>
</dependency>
<dependency>
	<groupId>com.ctrip.framework.apollo</groupId>
	<artifactId>apollo-client</artifactId>
	<version>1.5.1</version>
</dependency>
<dependency>
	<groupId>com.ctrip.framework.apollo</groupId>
	<artifactId>apollo-core</artifactId>
	<version>1.5.1</version>
</dependency>
<dependency>
	<groupId>com.github.ulisesbocchio</groupId>
	<artifactId>jasypt-spring-boot-starter</artifactId>
	<version>3.0.0</version>
</dependency>
<dependency>
	<groupId>com.google.inject</groupId>
	<artifactId>guice</artifactId>
	<version>4.1.0</version>
</dependency>
<dependency>
	<groupId>org.springframework.cloud</groupId>
	<artifactId>spring-cloud-starter-netflix-eureka-server</artifactId>
	<version>2.2.0.RELEASE</version>
</dependency>
<dependency>
	<groupId>com.google.code.gson</groupId>
	<artifactId>gson</artifactId>
	<version>2.8.5</version>
</dependency>
```
springmvc controller
```
@RestController
public class Resource {
	@Value("${test.value:default}")
	private String value;
	@GetMapping("/api/get")
	public String getValue() {
		return this.value;
	}
}
```
bootstrap.yml
```
spring: 
    application:
        name: rwbykit-test    
app:
    id: rwbykit-test
apollo: 
    meta: http://106.54.227.205:8080
    bootstrap:
        enabled: true 
        namespace: application
eureka: 
    client: 
        service-url: 
            defaultZone: http://127.0.0.1:8761/eureka/
 ```
 You can open this connection http://106.54.227.205:8070/ using apollo/admin, search project rwbykit-test,  When I first call the rest API 'http://localhost:8080/api/get' to get the value of the 'test.value' property value, modify the value of the a 'test.value' propertyand synchronize it to the client application, and then call the rest API, what he returns is still the old value , When I use the version below 2.0, I can update the property values dynamically through the Apollo config center, I checked the source code and found that used the cache when getting the property value, as follows  :
```
public Object getProperty(String name) {
    synchronized (this) {
        if (!cache.containsKey(name)) {
            Object resolved = getProperty(resolver, filter, delegate, name);
            if (resolved != null) {
                cache.put(name, resolved);
            }
        }
        return cache.get(name);
    }
}
```
 I wonder if caching can be turned on or off by config property

**Comment by ulisesbocchio** [comment]
Let me take a look at your stuff and I'll get back to you. Thanks for the details. Unfortunately there's no switch on/off for caching but you can definitely override the decryption bean and do your own thing. I'll see to add a flag in the future.
I didn't get a direct answer from you in regards of calling the `/refresh` endpoint. How are you triggering a "client refresh" after the config change?
Another thing I didn't understand...Are you saying that it worked with the previous version of jasypt-spring-boot and it broke on 3.0.0?
Caching has been present in jasypt-spring-boot since version 1

**Comment by rwbykit** [comment]
Thank you for your answer，Once again, I looked at the source code of Apollo and some previous versions of this project,  I found that caching was not used in version 2.0 of this project，but other versions used caching,  I'm sorry for what I said earlier, "when I use a version lower than 2.0, I can dynamically update the configuration through Apollo."   This is the code for getting property in version 2.0 
```
    @Override
    public Object getProperty(String name) {
        return getProperty(resolver, delegate, name);
    }
```
Now, I've published events for dynamically changing values so that I can get the modified values, but I'm not sure if this will cause other problems. I still insist on my point of view, whether we can add the switch of whether to turn on the cache or not

**Comment by ulisesbocchio** [comment]
@rwbykit did you figure it out?

**Comment by rwbykit** [comment]
yes,  I handled it by publishing refresh events

**Comment by skysliently** [comment]
hi，how did you handle it?

**Comment by skysliently** [comment]
> hi，how did you handle it?



> yes, I handled it by publishing refresh events

hi，how did you handle it?
