### ISSUE TITLE
Library source does not match the bytecode for class in 3.0.0

### ISSUE THREAD

**Issue by delor** [ulisesbocchio/jasypt-spring-boot#173]
I was looking at 3.0.0 code when IntelliJ showed a warning that:

> Library source does not match the bytecode for class EnableEncryptablePropertiesConfiguration

This is a bit concerning since jasypt is responsible for encrypting app secrets.

**Comment by ulisesbocchio** [comment]
You probably need to refresh your project. EnableEncryptablePropertiesConfiguration is a jasypt-spring-boot class, not a jasypt one.
