### ISSUE TITLE
jasypt-maven-plugin: Incorrect documentation

### ISSUE THREAD

**Issue by testphreak** [ulisesbocchio/jasypt-spring-boot#175]
Hi @rupert-madden-abbott and @ulisesbocchio, first off, thank you for providing a maven plugin for encrypting/decrypting secrets with jasypt. This is my first time using the plugin or Jasypt for that matter. So the feedback I am sharing below is from the context of a new user of your project(s). 

Having said that, I am not entirely sure if you actually tested the documentation you provided for the public in the [README](https://github.com/ulisesbocchio/jasypt-spring-boot/blob/master/README.md) related to using the [jasypt-maven-plugin](https://github.com/ulisesbocchio/jasypt-spring-boot/blob/master/README.md#maven-plugin) for string encryption/decryption purposes.

Here are a few issues I am running into:

1.  I did not find any [2.1.2](https://github.com/ulisesbocchio/jasypt-spring-boot/commit/9029e55efc13eb33623a5c1246e7bca2baf41c24#diff-04c6e90faac2675aa89e2176d2eec7d8R398) version of the plugin. I had to look at the plugin code, to figure out the correct version is `3.0.0`.
2. There is no [encrypt:encrypt](https://github.com/ulisesbocchio/jasypt-spring-boot/commit/9029e55efc13eb33623a5c1246e7bca2baf41c24#diff-04c6e90faac2675aa89e2176d2eec7d8R459) goal available. The correct goal from the code is `jasypt:encrypt`.
3. The plugin doesn't appear to support multi-profile yaml documents (introduced almost 3 years ago), which is what I use in my project. If multi-profile yaml isn't supported, it should be called out in the README.
4. If the lack of support for multi-profile yaml is indeed true, I don't see a section in the README that explains how one can actually encrypt secrets in the first place. Is the solution then to use the `jasypt-1.9.3.jar` to encrypt secrets and use your `spring-boot` or `spring-boot-starter` dependencies to decrypt already encrypted secrets? As said above, this is feedback coming from a first-time user. So if this is assumed all along, it would be good to mention in the README.

If you believe the issues I have listed above are inaccurate, please share or point me to an example of using the plugin to encrypt/decrypt secrets in multi-profile yaml documents.

**Comment by ulisesbocchio** [comment]
@testphreak:
1. Thanks, docs updated, you're right. 3.0.0 is the first version where the maven plugin is available
2. Not sure where you got `encrypt:encrypt` from, the doc states the correct goal [jasypt:encrypt](https://github.com/ulisesbocchio/jasypt-spring-boot#maven-plugin)
3. Noted, @rupert-madden-abbott can chime in here
4. Yes, people are using the jasypt jar to encrypt/decrypt since this is a companion library, most people are familiar with jasypt when they come here.

**Comment by rupert-madden-abbott** [comment]
2. Apologies, the goal is stated several times but only the first one is correct. This is because I have ported this from a plugin we were using internally in my organisation and we named the plugin internally the "encrypt" plugin but I felt that wasn't the best name when pushing it back upstream in order to open source it. The correct goals all begin with "jasypt:" not "encrypt:" and I will raise a PR on the README to fix that.

3. The plugin should work with any file type and there is an example of using it with a yaml file in the README (although with an incorrect goal as covered above). It would treat a single profile and multi-profile yaml file in exactly the same way. You would do this:

```
mvn jasypt:encrypt -Djasypt.encryptor.password="the password" -Djasypt.plugin.path="file:src/main/resources/application.yaml"
```

**Comment by ulisesbocchio** [comment]
@rupert-madden-abbott, I think @testphreak is talking about the spring config... when you load the empty spring application inside with the encryption config provided is no loading the proper profile that has the encryption config.
@testphreak can you try adding an extra arg to the command `-Dspring.active.profiles=yourProfile` ?

**Comment by testphreak** [comment]
@ulisesbocchio that's correct. The profile-specific config in the multi-document yaml doesn't seem to be getting picked up correctly by the plugin.

@rupert-madden-abbott here's what I see when I run the command - 
```
mvn jasypt:encrypt -Dspring.profiles.active=test -Djasypt.encryptor.password="secret" -Djasypt.plugin.path="file:/src/test/resources/demo.yml"
```

Output -
```
[INFO] The following profiles are active: test
[INFO] Post-processing PropertySource instances
[INFO] Converting PropertySource configurationProperties [org.springframework.boot.context.properties.source.ConfigurationPropertySourcesPropertySource] to AOP Proxy
[INFO] Converting PropertySource systemProperties [org.springframework.core.env.PropertiesPropertySource] to EncryptableMapPropertySourceWrapper
[INFO] Converting PropertySource systemEnvironment [org.springframework.boot.env.SystemEnvironmentPropertySourceEnvironmentPostProcessor$OriginAwareSystemEnvironmentPropertySource] to EncryptableSystemEnvironmentPropertySourceWrapper
[INFO] Converting PropertySource random [org.springframework.boot.env.RandomValuePropertySource] to EncryptablePropertySourceWrapper
[INFO] Property Filter custom Bean not found with name 'encryptablePropertyFilter'. Initializing Default Property Filter
[INFO] Started MavenCli in 0.793 seconds (JVM running for 2.307)
[INFO] Encrypting file /src/test/resources/environment-test.yml
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.417 s
[INFO] Finished at: 2019-12-02T19:00:18-08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.ulisesbocchio:jasypt-maven-plugin:3.0.0:encrypt (default-cli) on project jasypt-demo: Unable to read file /src/test/resources/environment-test.yml -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

**Comment by ulisesbocchio** [comment]
I see, the profile is actually being picked up but @rupert-madden-abbott added some code to try to pick up profile specific files instead of multi-profile files. @rupert-madden-abbott i think we should check if the profile specific file exists before feeding that to the process, and only pass the profile-specific file if it indeed exists

**Comment by ulisesbocchio** [comment]
this should be fixed in 3.0.2

**Comment by testphreak** [comment]
That's great! Thank you!

**Comment by prakashiit** [comment]
### Remove Extra '/' in filepath in Readme.md

@ulisesbocchio 
I faced this small problem while following the guide at "https://github.com/ulisesbocchio/jasypt-spring-boot/blob/master/README.md#file-path". For example, running
```
mvn encrypt:encrypt -Djasypt.encryptor.password="the password" -Djasypt.plugin.path="file:/src/main/resources/application.yml"
```
didn't work and after I changed the path to `-Djasypt.plugin.path="file:src/main/resources/application.yml"` (removed `/` before `src`), it worked perfectly. I'm not sure whether this was a typo in the readme or mine is just a unique case. Please correct if this was a typo, apologies if it's the latter. Thanks a lot for this plugin though!

**Comment by rupert-madden-abbott** [comment]
@prakashiit yes you are correct that this is a typo. It looks like PR #196 already fixes this one.
