### ISSUE TITLE
Unable to decrypt using jasypt-spring-boot-starter:3.0.1

### ISSUE THREAD

**Issue by A-Hassan-M** [ulisesbocchio/jasypt-spring-boot#183]
I am using spring boot:2.2.2.RELEASE when i tried to add jasypt functionality to hide my password i got the following error 
`Unable to decrypt: ENC(MyEncryptedPass). Decryption of Properties failed,  make sure encryption/decryption passwords match`
i used the command line to encrypt the password and decrypt it and it works fine so i am sure my encryption and decryption passwords are exact but i get this error when i try to launch my spring application. So any help (•–•)

**Comment by ulisesbocchio** [comment]
which command line? Jasypts original?
Jasypt alone has different encryption defaults than this library

**Comment by ulisesbocchio** [comment]
in 3.0.2 you can encrypt/decrypt single values from the command line (with the maven plugin) without having to use jasypt directly
