### ISSUE TITLE
Failed to execute goal com.github.ulisesbocchio:jasypt-maven-plugin:3.0.2:encrypt (default-cli) on project drone: Error Encrypting: Unable to read file /src/main/resources/application.yaml -> [Help 1]

### ISSUE THREAD

**Issue by gclm** [ulisesbocchio/jasypt-spring-boot#185]
As the title   

Spring Boot 2.2.2 

Execute instruction： 
```shell
mvn jasypt:encrypt -Djasypt.encryptor.password="encryptor" -Djasypt.plugin.path="file:/src/main/resources/application.yaml"
```

**We hope to get your help**

**Comment by cash1981** [comment]
Would be nice to get application*.yml support

**Comment by ulisesbocchio** [comment]
You can pass the path to the file you want to decrypt/encrypt properties from. Does that work?

**Comment by gclm** [comment]
No, currently only the .properties file can use the maven plugin, neither yml / yaml can be used. Both absolute and relative paths are used.

**Comment by ulisesbocchio** [comment]
Yaml should work, any text file should work if you pass the full path. Let me check what’s going on.

**Comment by ulisesbocchio** [comment]
Djasypt.plugin.path="file:/src/main/resources/application.yaml
That won’t work you have to pass the full path and  you’re starting with /src
