### ISSUE TITLE
password encrypted with jasypt is breaking when refreshed

### ISSUE THREAD

**Issue by krishna2025** [ulisesbocchio/jasypt-spring-boot#188]
we are using spring boot version 2.1.10.RELEASE and cloud version  Greenwich.SR3 and we are using jasypt for encrypted passwords. I kept encrypted passwords on application.yml file. During configserver startup it is getting decripted properly and working fine. If I make any changes on application.yml file  and hit bus/refresh, my decripted password automatically getting encrypted back and not decripting. Can some one help on this?

**Comment by benhouse1987** [comment]
same problem

**Comment by kamaydeo** [comment]
Yes. We are having the same issue. We recently enabled `spring.cloud.config.watch` and started seeing issues with properties. If I restart the application, it works fine again. There is definitely something happening on the refresh event. We are using Spring Boot 2.2.3 and Jasypt Spring Boot-Starter 2.1.2

**Comment by kamaydeo** [comment]
I just found out that this problem exists for Jasypt Spring Boot-Starter 1.16 as well as the latest version which is 3.0.2.

**Comment by ulisesbocchio** [comment]
Are you guys using the starter plugin?

**Comment by ulisesbocchio** [comment]
can you try version 3.0.3 that just went out?

**Comment by ulisesbocchio** [comment]
I got confirmation the refresh mechanism should be back in business from another issue #211, closing
