### ISSUE TITLE
I use spring but not use spring boot

### ISSUE THREAD

**Issue by frank780117** [ulisesbocchio/jasypt-spring-boot#19]
Hi,

I want to custom spring @propertySource annotation for jasypt.

but it's hard for me, and I find this project.

The project so cool, but I use spring 4, not use spring boot,

can this project use for spring? 

if can, give me a point or some hint, I want use this.

**Comment by ulisesbocchio** [comment]
Yeah, doesn't matter wether you use spring boot or not actually. You can follow the steps in the Readme and use jasypt-spring-boot without using the starter jar which basically is:
- add the jasypt-spring-boot dependency to your project's maven or gradle config.
- add the `@EnableEncryptableProperties` annotation to your main configuration class
That's it, now all your property sources should support encryption.
When you run your spring boot app, you'll have to provide the encryption password to your properties via command line using a system property: `-Djasypt.encryptor.password=yourPassword`

Please Star the repo if you find the library useful
