### ISSUE TITLE
新版本依赖失败，尝试各种都不行，

### ISSUE THREAD

**Issue by zhou9527** [ulisesbocchio/jasypt-spring-boot#197]
新版本依赖失败，尝试各种都不行， 2.1.0的看 。大佬求告知

**Comment by nightwolf11** [comment]
兄弟用英文！！speak English

**Comment by ulisesbocchio** [comment]
@zhou9527  I don't speak/read Chinese. Can you elaborate in English please?

**Comment by rupert-madden-abbott** [comment]
@zhou9527 

I think what you are saying is that the new version doesn't work for you and the last version that did is 2.1.0.

In version 3, the default encryption configuration changed. The changelog says:

    To keep your encrypted properties with previous default config use:

jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator


Does that help?
