### ISSUE TITLE
Failed to bind properties under 'spring.datasource.password' to java.lang.String

### ISSUE THREAD

**Issue by sagittar** [ulisesbocchio/jasypt-spring-boot#198]
spring.datasource.password=ENC(******)

Failed to bind properties under 'spring.datasource.password' to java.lang.String

**Comment by wanpeng2008** [comment]
same issue on spring-boot 2.2.4

**Comment by wanpeng2008** [comment]
Oh my issue is due to using the wrong algorithm.  It should match that in the command line.

**Comment by sagittar** [comment]
> same issue on spring-boot 2.2.4

how to fix thanks

**Comment by a-i-ks** [comment]
I have the same issue. The root cause seems to be a javax.crypto.BadPaddingException: Given final block not properly padded. Such issues can arise if a bad key is used during decryption

Any solution or workaround?

**Comment by linyongfu2013** [comment]
try use version 2.1.0

i use springboot 2.1.13 and jasypt 3.0.2 have the same issue, switch to 2.1.0 is ok.

**Comment by Jovons** [comment]
Added the following configuration, solved my same problem:
`jasypt.encryptor.iv-generator-classname=org.jasypt.iv.NoIvGenerator`
`jasypt.encryptor.algorithm=PBEWithMD5AndDES`

**Comment by kiqq** [comment]
This is caused by default algorithm change in 3.0.0 from `PBEWithMD5AndDES` to `PBEWITHHMACSHA512ANDAES_256` which required default iv-generator change from `org.jasypt.iv.NoIvGenerator` to `org.jasypt.iv.RandomIvGenerator`

There are few solutions:

- As Jovons wrote above. If you use algorithm which doesn't use iv generator add property: `jasypt.encryptor.iv-generator-classname=org.jasypt.iv.NoIvGenerator` or
- Downgrade to 2.1.2 or
- Switch to any algorithm that uses RandomIvGenerator.

**Comment by cobar79** [comment]
Same issue. Boot 2.3.2, jasypt 3.0.3, 2.1.2 regardless of iv-generator-classname NoIvGenerator or RandomIvGenerator
`jasypt:
  encryptor:
    password: fubar
    iv-generator-classname: org.jasypt.RandomIvGenerator

spring:
  password: ENC(yaddayaddayadda)
`

With or without @EnableAutoConfiguration
`
@SpringBootApplication
@EnableAutoConfiguration
`

Currently working in boot 2.2.4, jasypt 3.0.2 with encryptor.password in database

**Comment by zhanglinqiang** [comment]
I'm using spring-boot:2.5.0 and jasypt-maven-plugin:3.0.3, also met this problem. Finally I found that was mvn command parameter cause this. If you are using mvn command line please change 
```
mvn jasypt:encrypt-value -Djasypt.encryptor.password='secret' -Djasypt.plugin.value="password"
```
to
```
mvn jasypt:encrypt-value -Djasypt.encryptor.password=secret -Djasypt.plugin.value=password
```
Don't add any quotation marks.
