### ISSUE TITLE
Spring Cloud and jasypt-spring-boot-starter, not decrypting during refresh

### ISSUE THREAD

**Issue by krishna2025** [ulisesbocchio/jasypt-spring-boot#199]
@ramkumarar @jnulwliang @sathish593
 @nav16011991
I see in your post https://github.com/ulisesbocchio/jasypt-spring-boot/issues/112
above issue was resloved, can u please help how did u do that I followed few steps that did not work for me ? Can you share the code or explain Step by step process?

My current issue:
applicaiton-dev.yml
db2:
datasource:
jdbc-url: jdbc:db2://hostname:port/database:currentSchema=default
username:
password: ENC(cppertuvnh)
driverClassName: com.ibm.db2.jcc.DB2Driver
schema: default
spring:
datasource:
type: com.zaxxer.hikari.HikariDataSource
hikari:
connection-timeout: 20000
maximum-pool-size: 20
#minimum-idle: 2
#idle-timeout: 10000
pool-name: HikariConnectionPool
pool-prepared-statements: true

I'm using jasypt-spring-boot-starter (2.1.1) in a spring cloud config project.When the config loads for the first time from config server the encrypted values are getting properly decrypted. But when i do a refresh via actuator(https://hostName/dev1/actuator/bus-refresh/CspringAppName) endpoint the encrypted value is passed as is and not getting decrypted. Iam having following properties in cloud configuration and passing the password via JVM run time argument -Djasypt.encryptor.password=pass
I created
META-INF/spring.factories file in src/main/resources directory with below content but still no luck

org.springframework.cloud.bootstrap.BootstrapConfiguration=\
com.ulisesbocchio.jasyptspringboot.JasyptSpringBootAutoConfiguration

**Comment by gsakthinarayanan** [comment]
We face this problem as well. The Jasypt encrypted property is read correctly the first time but when that property or any other property is updated in the config repository, the encrypted property is then displayed as a plain text "ENC(....)" without being decrypted. We use springboot 2.2.6 with spring cloud Hoxton SR3. Any help/update on this will be much appreciated.

**Comment by dingbuoyi** [comment]
replace SpringApplication.run(YOUR_SPRING_BOOT_APPLICATION.class, args);
with 
`		new SpringApplicationBuilder()
				.environment(new StandardEncryptableEnvironment())
				.sources(YOUR_SPRING_BOOT_APPLICATION.class)
				.run(args);`

**Comment by ulisesbocchio** [comment]
thanks @dingbuoyi I still think there's something weird with the refresh but that should work also

**Comment by ulisesbocchio** [comment]
can you try version 3.0.3 that just went out?

**Comment by ulisesbocchio** [comment]
I got confirmation the refresh mechanism should be back in business from another issue #211, closing
