### ISSUE TITLE
Beans with @EnableConfigurationProperties are not properly instanciated.

### ISSUE THREAD

**Issue by carguel** [ulisesbocchio/jasypt-spring-boot#2]
Hi, 

I found an issue when using jasypt-spring-boot with a Spring configuration bean mapped from an application.yml file (see §23.7 at http://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html).

When @EnableEncryptableProperties is set, the configuration bean is not properly created. Properties of this bean that map a collection from the YAML file are not set. On the other side, it is correctly populated if @EnableEncryptableProperties is not set.

I pushed an example at [carguel/jasypt-spring-boot-sample](https://github.com/carguel/jasypt-spring-boot-sample). If you run the Main class, a NPE is raised when accessing the `items` collection from the `ItemConfig` class. This collection should be populated from the `items` nested node of the application.yml file.

I guess some initializations steps are missing in EnableEncryptablePropertySourcesPostProcessor.java.
But I could not find how to fix this.

**Comment by ulisesbocchio** [comment]
Alright, I see what you mean, thanks for the example. Let me take a look at what's going on and I'll come back to you soon

**Comment by ulisesbocchio** [comment]
It should work now. I noticed something strange in your demo app ItemConfig.java. @EnableConfigurationProperties should be declared in your Main.java and you should remove @Configuration. Also, @Value annotation should exist in @ConfigurationProperties annotated classes. What you need to do is to define setters for the properties to get properly populated.
I changed the Demo app in my repo to reflect your example, so check it out if you have any doubts.
Best,
Uli

**Comment by carguel** [comment]
Nice, my demo works perfectly now with your changes.

Thanks a lot.
