### ISSUE TITLE
Spring boot 3.0.1 - Jasypt version downgraded

### ISSUE THREAD

**Issue by srinivasarajuch** [ulisesbocchio/jasypt-spring-boot#201]
I have noticed that with jasypt-spring-boot 3.0.1 version has 1.9.3 version of jasypt. Where the prior version 2.1.0 has dependency as 1.9.4. Any specific reason why this was downgraded.

**Comment by rupert-madden-abbott** [comment]
From the changelog:

2.1.1: "and support for JSB96 with IV Generators". It looks like this was implemented in a fork of jasypt with version 1.9.4.

2.2.2: "jasypt 1.9.3 rollback with IV Generators". It looks like the support for IV Generators was integrated into this starter, and therefore, it could move back to using the official library.

**Comment by ulisesbocchio** [comment]
yup, 1.9.4 was not an "official" jasypt version.
