### ISSUE TITLE
how to hide the salt value

### ISSUE THREAD

**Issue by sun7852961** [ulisesbocchio/jasypt-spring-boot#202]
firstly，i cant write the salt value in code，its easy to decompile the code。but when i write the salt in command line when startup，it also can be seen in ”ps -ef”。
so， how to hide the salt value？

**Comment by sun7852961** [comment]
中文版再说说，怎么藏盐值啊。。命令行输入能被ps看到，写在jar里更容易看到。。

**Comment by sun7852961** [comment]
===============================================
well, the idea is that you don't put jasypt.encryptor.password in your properties. It's like having a door with a lock but hanging the key to the look on the door itself, it serves no purpose. What you have to do is keep the key safe and use it get in and out and locking the door behind you. Same here, you have to "inject" the encryption password when you needed, meaning when you run the application as an environment var/command line arg.
===========================================
environment var/command line is easy to see in ps -ef .  how to solve it

**Comment by sun7852961** [comment]
===============================================
well, the idea is that you don't put jasypt.encryptor.password in your properties. It's like having a door with a lock but hanging the key to the look on the door itself, it serves no purpose. What you have to do is keep the key safe and use it get in and out and locking the door behind you. Same here, you have to "inject" the encryption password when you needed, meaning when you run the application as an environment var/command line arg.
===========================================
environment var/command line is easy to see in ps -ef .  how to solve it

**Comment by sun7852961** [comment]
environment var/command line is easy to be seen in "ps -ef". how to slove it

**Comment by sun7852961** [comment]
the environment var can be seen in ‘’cat /proc/pid/environ‘’

**Comment by sumuchenshang** [comment]
可以把盐值放到另一个文件中，启动时加载文件中的盐值，启动后将那个文件删掉。

**Comment by sun7852961** [comment]
@sumuchenshang 多谢，跟我想的一样，我也是这样做的，这样唯一的risk就是他知道机制后可以用脚本不断dump那个配置文件的内容。。不过的确想不到其他方法了

**Comment by rupert-madden-abbott** [comment]
That attack vector is not solved by the use of this library.

Without this library, your sensitive properties are sitting in plaintext in the following locations:

* Version control
* Package manager
* Deployment environment

With this library, your properties are encrypted in all those places. But in a deployment environment, the application needs the encryption password to decrypt the encrypted properties. So yes, if your deployment environment is compromised, you have left the key right next to the locked door.

The point of this library is that if your version control or package manager is compromised, your properties are still secure.

Providing the encryption password via environment variables in the deployment environment is a standard and as secure as it gets way of getting it to your app. Your sensitive properties will always be vulnerable at the point of use. If your production servers are compromised then your encryption password being available is going to be the least of your worries.

**Comment by ulisesbocchio** [comment]
if someone can do a ps in your production machine that you don't want to you're in big trouble regardless of the encryption here, but just to entertain the thought you can source your env params from a file, or implement any other kind of ConfigurationPropertiesSource that suits your needs.
