### ISSUE TITLE
Version compatibility problem

### ISSUE THREAD

**Issue by sumuchenshang** [ulisesbocchio/jasypt-spring-boot#203]
When the development environment is JDK1.8+jasypt-spring-boot-starter 3.0.2, the project will fail to start.Only by lowering the version to 2.1.1 can the project start properly。Whether 3.0.2 requires a higher JDK version？

**Comment by rupert-madden-abbott** [comment]
I've just tried running a clean project on jasypt-spring-boot-starter 3.0.2 using JDK 1.8 and the project starts fine. As far as I can see, the starter both supports and intends to support JDK 1.8 in version 3.0.2.

What error are you getting? Can you upload a repository replicating the problem?
