### ISSUE TITLE
Difference Between BasicTextEncryptor and StandardPBEStringEncryptor

### ISSUE THREAD

**Issue by QGprogrammer** [ulisesbocchio/jasypt-spring-boot#204]
Jasypt is convenient，I like it much，but I hava some simple problems.
Forgive me for rough English.
Environment: JDK1.8 + Springboot2.1.5 
I have done the configuration in the application.yml
![image](https://user-images.githubusercontent.com/51161397/77493733-c6e43280-6e7e-11ea-9fa7-a345cbe148d2.png)
Encrpted by`StandardPBEStringEncryptor` for `spring.datasource.data-username`
When I run the application,console display this:

```
***************************
APPLICATION FAILED TO START
***************************

Description:

Failed to bind properties under 'spring.datasource.data-password' to java.lang.String:

    Reason: Failed to bind properties under 'spring.datasource.data-password' to java.lang.String

Action:

Update your application's configuration
```

But Encrpted by`BasicTextEncryptor` for `spring.datasource.data-username`
Application start normally.

So
I read the source about BasicTextEncryptor and StandardPBEStringEncryptor
And these points made me incomprehensive：
* What does `StringFixedIVGenerator` do
* What does `vi` mean
* Spring.datasource.data-username required java.lang.String, Why the code generated by StandardPBEStringEncryptor can't work.

If you are free please reply me
Thank u very much

**Comment by alexandrumm** [comment]
Hello,

Maybe I can help, so I would like to ask if your password or username is enclosed into `ENC(...)`. 
Example: `ENC(someEncryptedText)`

**Comment by QGprogrammer** [comment]
password or username are enclosed into ENC(...) correctly.
I guess the problem lies in the different encryption algorithms.

`BasicTextEncryptor basicTextEncryptor = new BasicTextEncryptor();
        StandardPBEStringEncryptor standardPBEStringEncryptor = new StandardPBEStringEncryptor();
        standardPBEStringEncryptor.setPassword("RcWXL");
        basicTextEncryptor.setPassword("RcWXL");
        String enstr1 = basicTextEncryptor.encrypt("root");
        String enstr2 = standardPBEStringEncryptor.encrypt("root");

        System.out.println("basicTextEncryptor:" + enstr1);// basicTextEncryptor:854mWbMImhmFjky/oWuFRA==
        System.out.println("standardPBEStringEncryptor:" + enstr2);  // standardPBEStringEncryptor:rIDvJumKLWNoPKGW/mvfqDhPqoIlZwlZQGLBojlqGIA=`

**Comment by rupert-madden-abbott** [comment]
@QGprogrammer 

I recommend you use the [jasypt-maven-plugin](https://github.com/ulisesbocchio/jasypt-spring-boot#maven-plugin) to encrypt the properties without providing any configuration except for the encryption password you want to use.

This will avoid you from having to construct your own encryptor and then try and get the configuration to match.

Does that help?
