### ISSUE TITLE
How to use jasypt.encryptor.password in Hibernate @TypeDef ?

### ISSUE THREAD

**Issue by wimdeblauwe** [ulisesbocchio/jasypt-spring-boot#21]
I am using jasypt-spring-boot and it works great for encypting properties in property files by passing `--jasypt.encryptor.password=mysecretpassword`. 

Is it also possible to use that property in the Hibernate annotation?

I currently have this:
```
@TypeDef(
        name = "encryptedInteger",
        typeClass = EncryptedIntegerAsStringType.class,
        parameters= {
                @Parameter(name="password", value="mysecretpassword")
        }
)
```

But that is obviously not very convenient as it hardcodes the password in the code.

**Comment by wimdeblauwe** [comment]
Never mind. Just found it myself.

First declare a `@Bean` in a `@Configuration` class like this:

```
    @Value("${jasypt.encryptor.password}")
    private String jasyptPassword;

 @Bean
    public HibernatePBEStringEncryptor hibernateIntegerEncryptor() {
        HibernatePBEStringEncryptor hibernatePBEStringEncryptor = new HibernatePBEStringEncryptor();
        hibernatePBEStringEncryptor.setRegisteredName("hibernateIntegerEncryptor");
        hibernatePBEStringEncryptor.setPassword(jasyptPassword);
        return hibernatePBEStringEncryptor;
    }
```

Then change the `@TypeDef` annotation to:

```
@TypeDef(
        name = "encryptedInteger",
        typeClass = EncryptedIntegerAsStringType.class,
        parameters= {
                @Parameter(name="encryptorRegisteredName", value="hibernateIntegerEncryptor")
        }
)
```

Then in your entity:

```
    @Type(type = "encryptedInteger")
    private int x;
```

**Comment by ulisesbocchio** [comment]
Cool, so it allows you to reference the encryptor by name in the TypeDef but, what picks it up from the Spring Context? Just curious, since you are using "setRegisteredName" it seems that there's a registry being kept somewhere.

**Comment by wimdeblauwe** [comment]
I have no idea how it works internally. I used the [documentation about the hibernate integration](http://www.jasypt.org/hibernate.html) on the Jasypt website to come to this.
