### ISSUE TITLE
When I use this, I cannot change the property value dynamically 

### ISSUE THREAD

**Issue by rwbykit** [ulisesbocchio/jasypt-spring-boot#211]
1: Custom propertysource object
2: Add the custom PropertySource object to the ConfigurableEnvironment (StandardServletEnvironment) object
3: Then RefreshScopeRefreshedEvent is published
4: It is found that the cache property configuration converted by CachegDelegateEncryptablePropertySource has not been cleared, that is, it has not been refreshed, resulting in the modified value in the custom PropertySource object not taking effect
Reason: the environment variable in the RefreshScopeRefreshedEventListener class is actually a StandardEnvironment object, and it cannot refresh the list of PropertySource in the corresponding StandardServletEnvironment, but the custom PropertySource object is proxy by the CachegDelegateEncryptablePropertySource object
 Now, how should I deal with this situation ？

**Comment by rupert-madden-abbott** [comment]
Do you want properties in your custom property source to be encrypted? If not then you could [skip them](https://github.com/ulisesbocchio/jasypt-spring-boot#filter-out-propertysource-classes-from-being-introspected).

**Comment by ulisesbocchio** [comment]
there are a few open issues with the refresh mechanism. Until they're resolved you should use the `StandardEncryptableEnvironment` directly on your `SpringApplicationBuilder`

**Comment by ulisesbocchio** [comment]
can you try version 3.0.3 that just went out?

**Comment by rwbykit** [comment]
I tried to use the 3.0.3 version. my problem no longer exists. thank you
