### ISSUE TITLE
Feature request for jasypt-maven-plugin: Re-encrypt with new settings

### ISSUE THREAD

**Issue by springfan** [ulisesbocchio/jasypt-spring-boot#214]
In order to re-encrypt all credentials with a new password I have to:
1) Decrypt all credentials (one command thanks to jasypt-maven-plugin)
2) Surround all to be encrypted strings with DEC()
3) Encrypt all credentials (one command thanks to jasypt-maven-plugin)

It would be great if the plugin could output all decrypted credentials with DEC() or to take over of the whole process and provide a command to re-encrypt all previously encrypted strings with a new password / jasypt settings.

**Comment by springfan** [comment]
It looks like the default decrypt output does already put the values inside DEC(). That's contrary to the README that states:

> Which would output the decrypted contents to the screen:
> `sensitive.password=ENC(encrypted)`
> `regular.property=example`

It should state
`sensitive.password=DEC(unencrypted)`

**Comment by rupert-madden-abbott** [comment]
@springfan I've pushed a PR that implements your request.

I figured there were two main use cases:

* User is relying on default config and upgrades to a new version with new default configuration (i.e. like how the defaults changed from 2 to 3). They want a one click way of re-encrypting with the new config. For this, I've added the upgrade goal.
* User wants to change some aspect of their config e.g. they want to re-encrypt with a new password. For this, I've added the reencrypt goal.

If you want to see if these fit your requirements, you can checkout the branch associated with the PR from my fork, then install with mvn install, then update your project to use version 3.0.3-SNAPSHOT. The README has been updated to explain how to use.

Any feedback is welcome.

I've also fixed the documentation issue you raised.
