### ISSUE TITLE
Failed to bind properties under 'spring.mail.password' to java.lang.String

### ISSUE THREAD

**Issue by amithksm** [ulisesbocchio/jasypt-spring-boot#222]
Referring to the last comment in the issue <https://github.com/ulisesbocchio/jasypt-spring-boot/issues/154>. I am not able to use Jasypt encryption to spring.mail.password property in JavaMailSender. Getting the error message as mentioned in the title when version 3.0.3 was used. When I downgraded version 2.0.0 the issue was resolved.

**Comment by Niinetan** [comment]
The default algorithm of maven tool 3.0.3 is different from the one of starter 3.0.3.

**Comment by costalopes71** [comment]
Hey guys...
I faced the same problem as you all... I could make it work by doing the following:

- 1st: encrypt your password using PBEWithMD5AndTripleDES algorithm, example:
`
./encrypt.sh input="admin123" password=<myEncryptionPassword> algorithm=PBEWithMD5AndTripleDES
`

- 2st: After doing that, in your application.properties include these properties:
```
jasypt.encryptor.password=<yourPassword>
jasypt.encryptor.iv-generator-classname=org.jasypt.iv.NoIvGenerator
jasypt.encryptor.algorithm=PBEWithMD5AndTripleDES
```

It worked fine for me.
Im using:
jasypt-spring-boot-starter 3.0.3
spring-boot 2.4.2

Hope that help you guys.
Cheers
