### ISSUE TITLE
Error: org.springframework.beans.factory.BeanCurrentlyInCreationException: Error creating bean with name 'encryptablePropertyResolver': Requested bean is currently in creation: Is there an unresolvable circular reference?

### ISSUE THREAD

**Issue by 871225223** [ulisesbocchio/jasypt-spring-boot#225]
i want to use custom  EncryptablePropertyResolver function, but i got this issue;
use spring-boot-2.1.9Release, jasypt-spring-boot 2.1.2,
the  prefixes, suffixes, EncryptablePropertyDetector and StringEncryptor have been overrided

**Comment by ulisesbocchio** [comment]
will be solved in 3.0.4
