### ISSUE TITLE
spring.main.allow-bean-definition-overriding lose config

### ISSUE THREAD

**Issue by cuber2simple** [ulisesbocchio/jasypt-spring-boot#227]
<dependency>
        <groupId>com.github.ulisesbocchio</groupId>
        <artifactId>jasypt-spring-boot-starter</artifactId>
        <version>3.0.3</version>
      </dependency>
      <dependency>
        <groupId>com.alibaba.cloud</groupId>
        <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
        <version>2.2.1.RELEASE</version>
      </dependency>
import jasypt the feign overriding setting will failover.......

**Comment by javaerHei** [comment]
help!!!

**Comment by zzujustme** [comment]
help!!!

**Comment by zzujustme** [comment]
> com.github.ulisesbocchio jasypt-spring-boot-starter 3.0.3 com.alibaba.cloud spring-cloud-starter-alibaba-nacos-discovery 2.2.1.RELEASE import jasypt the feign overriding setting will failover.......

解决掉了吗

**Comment by zzujustme** [comment]
> help!!!

解决了吗

**Comment by whbhhh** [comment]
碰到同样的问题 请求如何解决的？

**Comment by k631583871** [comment]
使用jasypt 框架后 
在bootstrap.yml 中配置
spring:
  main:
    allow-bean-definition-overriding: true
在bootstrap 阶段 正常，启动阶段会发生 这个属性丢失。

我的临时解决方法是在  application.yml 中 再写一遍
spring:
  main:
    allow-bean-definition-overriding: true

**Comment by ulisesbocchio** [comment]
I don't understand a word of what's being discussed her... care to explain?

**Comment by k631583871** [comment]
jasypt.encryptor.bootstrap=true 
这个属性为 true的时候 ， 日志开头就会出现 app_name_IS_UNDEFINED ，无法获取名字的问题  当 false的时候，就正常
项目源码 [demo-jasypt.zip](https://github.com/ulisesbocchio/jasypt-spring-boot/files/7682083/demo-jasypt.zip)
![20211209114919](https://user-images.githubusercontent.com/15627274/145331360-c98e863b-c8c8-449c-b104-2a247d5ec4a1.png)

**Comment by k631583871** [comment]
@ulisesbocchio  Is the information I provided helpful?

**Comment by xiaomizhou95** [comment]
@ulisesbocchio The introduction of a dependency will result in  "spring.main.allow-bean-definition-overriding" property Forced closure

**Comment by xiaomizhou95** [comment]
@k631583871 想咨询一下  这个jasypt.encryptor.bootstrap 属性是干什么的，为什么关闭了它就不报 spring.main.allow-bean-definition-overriding失效了

**Comment by k631583871** [comment]
@xiaomizhou95 我觉得这个是一个问题,正常应用的 bootstrap 阶段配置是可以传递给 application 的. 但是引入jasypt ,就造成配置无法传递下去.  要是 bootstrap阶段没有需要加密的配置,可以 jasypt.encryptor.bootstrap=false  这样配置来关闭这个功能来解决问题

**Comment by xiaomizhou2** [comment]
> @xiaomizhou95 我觉得这个是一个问题,正常应用的 bootstrap 阶段配置是可以传递给 application 的. 但是引入jasypt ,就造成配置无法传递下去. 要是 bootstrap阶段没有需要加密的配置,可以 jasypt.encryptor.bootstrap=false 这样配置来关闭这个功能来解决问题

好的  谢谢
