### ISSUE TITLE
can not work with spring.redis.password

### ISSUE THREAD

**Issue by p0mp0k0** [ulisesbocchio/jasypt-spring-boot#228]
application.yml
jasypt:
  encryptor:
    password: LS
    algorithm: PBEWithMD5AndDES

application-dev.yml
spring:
  redis:
      password: ENC(T9romiESsRvi8nfRe3gcYtzrA54+jNJE)

2020-07-06 02:45:22 [main] INFO  com.ls.mngsrv.MngSrvApplication
 - The following profiles are active: dev
2020-07-06 02:45:24 [main] INFO  c.u.j.c.EnableEncryptablePropertiesBeanFactoryPostProcessor
 - Post-processing PropertySource instances
2020-07-06 02:45:24 [main] INFO  c.u.j.EncryptablePropertySourceConverter
 - Converting PropertySource configurationProperties [org.springframework.boot.context.properties.source.ConfigurationPropertySourcesPropertySource] to AOP Proxy
2020-07-06 02:45:24 [main] INFO  c.u.j.EncryptablePropertySourceConverter
 - Converting PropertySource servletConfigInitParams [org.springframework.core.env.PropertySource$StubPropertySource] to EncryptablePropertySourceWrapper
2020-07-06 02:45:24 [main] INFO  c.u.j.EncryptablePropertySourceConverter
 - Converting PropertySource servletContextInitParams [org.springframework.core.env.PropertySource$StubPropertySource] to EncryptablePropertySourceWrapper
2020-07-06 02:45:24 [main] INFO  c.u.j.EncryptablePropertySourceConverter
 - Converting PropertySource systemProperties [org.springframework.core.env.PropertiesPropertySource] to EncryptableMapPropertySourceWrapper
2020-07-06 02:45:24 [main] INFO  c.u.j.EncryptablePropertySourceConverter
 - Converting PropertySource systemEnvironment [org.springframework.boot.env.SystemEnvironmentPropertySourceEnvironmentPostProcessor$OriginAwareSystemEnvironmentPropertySource] to EncryptableSystemEnvironmentPropertySourceWrapper
2020-07-06 02:45:24 [main] INFO  c.u.j.EncryptablePropertySourceConverter
 - Converting PropertySource random [org.springframework.boot.env.RandomValuePropertySource] to EncryptablePropertySourceWrapper
2020-07-06 02:45:24 [main] INFO  c.u.j.EncryptablePropertySourceConverter
 - Converting PropertySource applicationConfig: [classpath:/application-dev.yml] [org.springframework.boot.env.OriginTrackedMapPropertySource] to EncryptableMapPropertySourceWrapper
2020-07-06 02:45:24 [main] INFO  c.u.j.EncryptablePropertySourceConverter
 - Converting PropertySource applicationConfig: [classpath:/application.yml] [org.springframework.boot.env.OriginTrackedMapPropertySource] to EncryptableMapPropertySourceWrapper
2020-07-06 02:45:24 [main] INFO  c.u.j.f.DefaultLazyPropertyFilter
 - Property Filter custom Bean not found with name 'encryptablePropertyFilter'. Initializing Default Property Filter
2020-07-06 02:45:25 [main] INFO  c.u.j.r.DefaultLazyPropertyResolver
 - Property Resolver custom Bean not found with name 'encryptablePropertyResolver'. Initializing Default Property Resolver
2020-07-06 02:45:25 [main] INFO  c.u.j.d.DefaultLazyPropertyDetector
 - Property Detector custom Bean not found with name 'encryptablePropertyDetector'. Initializing Default Property Detector
2020-07-06 02:45:25 [main] WARN  io.undertow.websockets.jsr
 - UT026010: Buffer pool was not set on WebSocketDeploymentInfo, the default pool will be used
2020-07-06 02:45:25 [main] INFO  io.undertow.servlet
 - Initializing Spring embedded WebApplicationContext
2020-07-06 02:45:25 [main] INFO  c.u.j.encryptor.DefaultLazyEncryptor
 - String Encryptor custom Bean not found with name 'jasyptStringEncryptor'. Initializing Default String Encryptor
2020-07-06 02:45:25 [main] INFO  c.u.j.c.StringEncryptorBuilder
 - Encryptor config not found for property jasypt.encryptor.key-obtention-iterations, using default value: 1000
2020-07-06 02:45:25 [main] INFO  c.u.j.c.StringEncryptorBuilder
 - Encryptor config not found for property jasypt.encryptor.pool-size, using default value: 1
2020-07-06 02:45:25 [main] INFO  c.u.j.c.StringEncryptorBuilder
 - Encryptor config not found for property jasypt.encryptor.provider-name, using default value: null
2020-07-06 02:45:25 [main] INFO  c.u.j.c.StringEncryptorBuilder
 - Encryptor config not found for property jasypt.encryptor.provider-class-name, using default value: null
2020-07-06 02:45:25 [main] INFO  c.u.j.c.StringEncryptorBuilder
 - Encryptor config not found for property jasypt.encryptor.salt-generator-classname, using default value: org.jasypt.salt.RandomSaltGenerator
2020-07-06 02:45:25 [main] INFO  c.u.j.c.StringEncryptorBuilder
 - Encryptor config not found for property jasypt.encryptor.iv-generator-classname, using default value: org.jasypt.iv.RandomIvGenerator
2020-07-06 02:45:25 [main] INFO  c.u.j.c.StringEncryptorBuilder
 - Encryptor config not found for property jasypt.encryptor.string-output-type, using default value: base64
2020-07-06 02:45:25 [main] WARN  o.s.b.w.s.c.AnnotationConfigServletWebServerApplicationContext
 - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is java.lang.RuntimeException: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'jwtAuthenticationTokenFilter': Unsatisfied dependency expressed through field 'tokenService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'tokenService': Unsatisfied dependency expressed through field 'redisCache'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'redisCache': Unsatisfied dependency expressed through field 'redisTemplate'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'redisTemplate' defined in class path resource [com/ruoyi/framework/config/RedisConfig.class]: Unsatisfied dependency expressed through method 'redisTemplate' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.springframework.boot.autoconfigure.data.redis.LettuceConnectionConfiguration': Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.boot.context.properties.ConfigurationPropertiesBindException: Error creating bean with name 'spring.redis-org.springframework.boot.autoconfigure.data.redis.RedisProperties': Could not bind properties to 'RedisProperties' : prefix=spring.redis, ignoreInvalidFields=false, ignoreUnknownFields=true; nested exception is org.springframework.boot.context.properties.bind.BindException: Failed to bind properties under 'spring.redis.password' to java.lang.String
2020-07-06 02:45:25 [main] ERROR o.s.b.d.LoggingFailureAnalysisReporter
 - 

***************************
APPLICATION FAILED TO START
***************************

Description:

Failed to bind properties under 'spring.redis.password' to java.lang.String:

    Reason: Failed to bind properties under 'spring.redis.password' to java.lang.String

Action:

Update your application's configuration

**Comment by hdatsf** [comment]
The default config [jasypt.encryptor.iv-generator-classname] is changed, please set it to [org.jasypt.iv.NoIvGenerator] and try it.

**Comment by ulisesbocchio** [comment]
that was a major version release that contained breaking changes and the IV Generator changes have been documented in the Readme with instructions on how to keep the backwards compatibility. This happens in all software.
