### ISSUE TITLE
Should configurationsProperties be wrapped/proxied at all

### ISSUE THREAD

**Issue by smaldini** [ulisesbocchio/jasypt-spring-boot#230]
Hey, with Spring Boot 2.3 we have a new caching property behavior used by configurationsProperties (`ConfigurationPropertySourcesPropertySource` ). Unfortunately the encryptable AOP is applied to it as checked via (https://github.com/ulisesbocchio/jasypt-spring-boot/blob/3715d61d9a887ab471eeb52434cd13fcffec50f2/jasypt-spring-boot/src/main/java/com/ulisesbocchio/jasyptspringboot/EncryptablePropertySourceConverter.java#L124).

I was wondering if we need to aop this composite configurationProperties as it does delegate to individual prop source ?

**Comment by ulisesbocchio** [comment]
Could be, what’s the issue you’re seeing? Since it’s a property source even though it is composite it should be ok to aop/wrap at the top

**Comment by ulisesbocchio** [comment]
should be fixed in 3.0.4
