### ISSUE TITLE
License file is inconsistent with maven repository 

### ISSUE THREAD

**Issue by eoinreilly93** [ulisesbocchio/jasypt-spring-boot#235]
I have to provide license information at work when requesting to use third party software, and when doing so for this project I've noticed that the license provided here on [github](https://github.com/ulisesbocchio/jasypt-spring-boot/blob/master/LICENSE) is the MIT license, but on the [maven repository ](https://mvnrepository.com/artifact/com.github.ulisesbocchio/jasypt-spring-boot-starter/3.0.3) it says it is licensed under the Apache 2.0 license. 

Which of these two is the correct license?

**Comment by ulisesbocchio** [comment]
good catch, thanks, will fix this next release
