### ISSUE TITLE
support relaxed binding for encrypted application.properties

### ISSUE THREAD

**Issue by deepak-khedkar** [ulisesbocchio/jasypt-spring-boot#237]
in application.properties

this works :-
 some.property=ENC(fd0TI09wu+myz1pXNGXy3g==)

this doesn't work 
     some.property=${ENV_PASS:ENC(fd0TI09wu+myz1pXNGXy3g==)}
or some.property=ENC(${ENV_PASS:fd0TI09wu+myz1pXNGXy3g==}) 

or is there any other way to get encrypted string from env ?

**Comment by ulisesbocchio** [comment]
this should work in 3.0.4
