### ISSUE TITLE
Jasypt decrypts only the encrypted fields which are defined under src/main/resources/application.properties but not under src/main/resource/custom-properties/sample.properties

### ISSUE THREAD

**Issue by ssivastars** [ulisesbocchio/jasypt-spring-boot#239]
Jasypt decrypts only the encrypted fields which are defined under src/main/resources/application.properties but not under src/main/resource/custom-properties/sample.properties

Is there any alternative way to do this?

**Comment by rupert-madden-abbott** [comment]
How are you reading the properties?

Jasypt will only decrypt properties you make it aware of. The custom location you reference is not one that would get picked up by Spring Boot by default so you would need to include it somehow. You need to refer to the Spring Boot documentation on external configuration loading.

If you are trying to decrypt using the Maven plugin then you need to use an additional parameter: https://github.com/ulisesbocchio/jasypt-spring-boot#changing-the-file-path

**Comment by ssivastars** [comment]
@rupert-madden-abbott Yeah I am using maven plugin. the link you have shared gave me some insights to resolve my issue. thank you very much for kind reply.
