### ISSUE TITLE
jasypt-spring-boot dependency problem

### ISSUE THREAD

**Issue by AntonyM55** [ulisesbocchio/jasypt-spring-boot#240]
Please forgive my bad english, 
 1. jasypt-spring-boot 2.1.1              using com.melloware.jasypt 1.9.4
2.jasypt-spring-boot 2.1.2 ~ 3.0.3 using org.jasypt.jasypt          1.9.3

if you using  jasypt-spring-boot 2.1.1  create password using PBEWITHHMACSHA512ANDAES_256   
config.setAlgorithm("PBEWITHHMACSHA512ANDAES_256");
config.setIvGeneratorClassName("org.jasypt.salt.RandomIVGenerator");

and you can't use this password in asypt-spring-boot  3.0.3 version because is will use "org.jasypt.iv.NoIvGenerator" by default, I changed pom.xml to this
		&lt;dependency&gt;
			&lt;groupId&gt;com.github.ulisesbocchio&lt;/groupId&gt;
			&lt;artifactId&gt;jasypt-spring-boot-starter&lt;/artifactId&gt;
			&lt;version&gt;3.0.3&lt;/version&gt;
			&lt;exclusions&gt;
				&lt;exclusion&gt;
					&lt;groupId&gt;org.jasypt&lt;/groupId&gt;
					&lt;artifactId&gt;jasypt&lt;/artifactId&gt;
				&lt;/exclusion&gt;
			&lt;/exclusions&gt;
		&lt;/dependency&gt;
		&lt;dependency&gt;
			&lt;groupId&gt;com.melloware&lt;/groupId&gt;
			&lt;artifactId&gt;jasypt&lt;/artifactId&gt;
			&lt;version&gt;1.9.4&lt;/version&gt;
		&lt;/dependency&gt;

after this I can use 
jasypt.encryptor.algorithm=PBEWITHHMACSHA512ANDAES_256
jasypt.encryptor.iv-generator-classname=org.jasypt.salt.RandomIVGenerator

**Comment by luanweijie** [comment]
https://github.com/ulisesbocchio/jasypt-spring-boot/#update-11242019-version-300-release-includes
After version 3.3, please follow the instructions below
To keep your encrypted properties with previous default config use:
jasypt:
encryptor:
algorithm: PBEWithMD5AndDES
iv-generator-classname: org.jasypt.iv.NoIvGenerator

**Comment by ulisesbocchio** [comment]
thanks @luanweijie
