### ISSUE TITLE
spring boot start 3.0.3  throw exception: 'spring.datasource.password' to java.lang.String

### ISSUE THREAD

**Issue by startjava** [ulisesbocchio/jasypt-spring-boot#241]
i want use 3.0.3 new version
,but i do not want show the exception,
how do is ok?

thank you !

**Comment by cobar79** [comment]
See https://github.com/ulisesbocchio/jasypt-spring-boot/issues/238

**Comment by luanweijie** [comment]
https://github.com/ulisesbocchio/jasypt-spring-boot/#update-11242019-version-300-release-includes
Atter the version 3.0.0,
To keep your encrypted properties with previous default config use:
jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator

**Comment by Draymond-TS** [comment]
> https://github.com/ulisesbocchio/jasypt-spring-boot/#update-11242019-version-300-release-includes
> After version 3.0, please follow the instructions below
> To keep your encrypted properties with previous default config use:
> jasypt:
> encryptor:
> algorithm: PBEWithMD5AndDES
> iv-generator-classname: org.jasypt.iv.NoIvGenerator
> 
> because the version 3.0.0 later, the default iv-generator-classname are org.jasypt.iv.RandomIvGenerator

Thx,bro,According to you, I've fixed the bug.Thanks again bro.

**Comment by ulisesbocchio** [comment]
thanks again @luanweijie
