### ISSUE TITLE
spring boot /env fails if overriding with an external encrypted property file

### ISSUE THREAD

**Issue by linead** [ulisesbocchio/jasypt-spring-boot#26]
If we provide an encrypted property and password within the war (for db password) and then override this in the deployment environment with another encrypted property and jasypt password then the /env endpoint will throw an exception as it's unable to decrypt the original property from the embedded property. 

I understand why this is happening, but it would be nice if it just skipped the undecryptable property.

Cheers,
Daniel.

**Comment by ulisesbocchio** [comment]
Hi buddy, thanks for using the library. I'm a bit lost with your issue. You set the password and have an encrypted property, right? what you mean with "override this in the deployment environment"? Do you have a git repo where the issue manifests?

Best,
Uli

**Comment by ulisesbocchio** [comment]
any input you can provide here?
