### ISSUE TITLE
Use vm options, it cannot start

### ISSUE THREAD

**Issue by pudding1019** [ulisesbocchio/jasypt-spring-boot#270]
I user jasypt-spring-boot-starter 3.0.3 encrypt my configuration,I use vm options -Djasypt.encryptor.password=hello -Djasypt.encryptor.algorithm=PBEWITHHMACSHA512ANDAES_256 -Djasypt.encryptor.iv-generator-classname=org.jasypt.iv.RandomIvGenerator in idea,app starts normally,After typing into a jar package and using vm options, it can’t be started anymore，
![image](https://user-images.githubusercontent.com/23228684/114415601-69826700-9be2-11eb-9c05-5c06daaf3f1c.png)

**Comment by ulisesbocchio** [comment]
3.0.4 released
