### ISSUE TITLE
jasypt3.0.3 does not support Nacos @NacosConfigurationProperties automatic decryption

### ISSUE THREAD

**Issue by yanhu32** [ulisesbocchio/jasypt-spring-boot#275]
``package com.example.dynamicdb.config;

import com.alibaba.nacos.api.config.annotation.NacosConfigurationProperties;
import lombok.extern.slf4j.Slf4j;
import org.springframework.boot.autoconfigure.jdbc.DataSourceProperties;
import org.springframework.context.annotation.Primary;
import org.springframework.stereotype.Component;

/**
 * @author yh
 * @since 2021/6/9
 */
@Slf4j
@Primary
@Component
@NacosConfigurationProperties(dataId = "mysql-hikari", groupId = "datasource", prefix = "spring.datasource", autoRefreshed = true)
public class DynamicDataSourceProperties extends DataSourceProperties {

}

**Comment by ulisesbocchio** [comment]
3.0.5 is out. Reopen if still an issue
