### ISSUE TITLE
Doesn't work with Java 1.6

### ISSUE THREAD

**Issue by depandey** [ulisesbocchio/jasypt-spring-boot#28]
Can you please make it compatible with Java 1.6

ERROR:

com.ulisesbocchio.jasyptspringboot.annotation.EnableEncryptableProperties
[ERROR] bad class file: com/ulisesbocchio/jasyptspringboot/annotation/EnableEncryptableProperties.class(com/ulisesbocchio/jasyptspringboot/annotation:EnableEncryptableProperties.class)
[ERROR] class file has wrong version 52.0, should be 50.0

**Comment by ulisesbocchio** [comment]
I could do a one off to help you but it'd take me a while. If you need it asap, I suggest you fork it, grab the java7 branch and change the targets in the parent pom to 1.6, see what breaks and fix it. Should be only minor syntax errors if anything.

**Comment by naeem** [comment]
Have a look at https://github.com/fingerprints/jasypt-spring-boot

@ulisesbocchio please create a java6 branch and you can merge my changes.
I created my branch from master and not java 7.

**Comment by naeem** [comment]
@ulisesbocchio Please have a look at https://github.com/fingerprints/jasypt-spring-boot
There is a java6 branch based on the java7 branch.
I did not test the tomcat ssl part as yet.

**Comment by ulisesbocchio** [comment]
Thanks man, appreciate it. Will create that branch

**Comment by ulisesbocchio** [comment]
Alright, branch created and your code has been merged to it. Will do a few tests shortly and if everything's good I'll create a release soon.
Thanks!

**Comment by depandey** [comment]
Thanks a lot :)

**Comment by ulisesbocchio** [comment]
alright version 1.5-java6 is out of the door, just released, wait until it shows up in maven2 repo and you'll be ready to go.
