### ISSUE TITLE
jasypt:decrypt fails with Yaml file 

### ISSUE THREAD

**Issue by henka-rl** [ulisesbocchio/jasypt-spring-boot#288]
When trying to decrypt application.yml with `mvn jasypt:decrypt -Djasypt.encryptor.password="{password}" -Djasypt.plugin.path="file:src/main/resources/application.yml"` it fails with this error:
Error Decrypting: null: EncryptionOperationNotPossibleException

`mvn jasypt:encrypt -Djasypt.encryptor.password="{password}" -Djasypt.plugin.path="file:src/main/resources/application.yml"` works just fine

**Comment by ulisesbocchio** [comment]
what type of encryption are you using? symmetric or asymmetric?

**Comment by henka-rl** [comment]
I run the command again today and now it works just fine...
