### ISSUE TITLE
Data not in AES persited

### ISSUE THREAD

**Issue by KaijuDeluxe** [ulisesbocchio/jasypt-spring-boot#291]
Hi, got the following code, but its not in AES saved. When i pull data with the following Query, i dont get the String, instead i get some 

Query to check if data are decodec correctly
`SELECT AES_ENCRYPT(empfaenger_name, 'secret-key-zJs4Nz.e!BN4eJ.sDuwrYdty@tNnm2K8J8s@4D!EkJWY')
FROM umsatz`

Get
<img width="891" alt="image" src="https://user-images.githubusercontent.com/39457956/134240597-51c100dd-49cc-4741-ac0d-d0c04871574e.png">

The Data itseld looks like this (Basse64 Style?)
<img width="536" alt="image" src="https://user-images.githubusercontent.com/39457956/134240752-29833617-70f4-4315-abae-d03271fe212f.png">

My Code
`@Configuration
public class HibernateConfig {
    @Value("${aes.key}")
    private String jasyptPassword;
    @Bean
    public HibernatePBEStringEncryptor hibernateIntegerEncryptor() {
        HibernatePBEStringEncryptor hibernatePBEStringEncryptor = new HibernatePBEStringEncryptor();
        hibernatePBEStringEncryptor.setRegisteredName("hibernateIntegerEncryptor");
        hibernatePBEStringEncryptor.setAlgorithm("PBEWITHMD5ANDDES");
        hibernatePBEStringEncryptor.setPassword(jasyptPassword);
        return hibernatePBEStringEncryptor;
    }
}`

`@Entity
@Table(name = "umsatz")
@TypeDef(
        name="encryptedString",
        typeClass=EncryptedStringType.class,
        parameters= {
                @Parameter(name="encryptorRegisteredName", value="hibernateIntegerEncryptor")
        }
)
public class Umsatz {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;
    @Type(type="encryptedString")
    String empfaengerName;
//Getter Setter
}`

application.properties (generated Key with the webtool, this is correct database login works as aspected)
`aes.key=ENC(RsH82YF6zrW7Sf1lKUOe9fVL8qcnwBtex..............Gi8EqApGb1/4aoxB5u/5VQW0kb2flEJMzA==)`

Is there anyone who can help me out?

**Comment by ulisesbocchio** [comment]
I'm not sure I'm following....
Are you using a StringEncryptor from jasypt to implement that `EncryptedStringType` and you're concocting?
When you say "the data itself looks like this..." it looks like the encryption worked.... I'd assume you have a problem decrypting it back. What database type is it stored as? String/Text?

I would need to see
 your implementation of `EncryptedStringType` and `HibernatePBEStringEncryptor`

**Comment by KaijuDeluxe** [comment]
Hi thanks for your answer. The HibernatePBEStringEncryptor:

`@Configuration
public class HibernateConfig {
    @Value("${aes.key}")
    private String jasyptPassword;
    
    @Bean
    public HibernatePBEStringEncryptor hibernateIntegerEncryptor() {
        HibernatePBEStringEncryptor hibernatePBEStringEncryptor = new HibernatePBEStringEncryptor();
        hibernatePBEStringEncryptor.setRegisteredName("hibernateIntegerEncryptor");
        hibernatePBEStringEncryptor.setAlgorithm("PBEWITHMD5ANDDES");
        hibernatePBEStringEncryptor.setPassword(jasyptPassword);
        return hibernatePBEStringEncryptor;
    }
}`

EncryptedStringType i dont have implementend, its from the package `org.jasypt.hibernate5.type.EncryptedStringType;`

Is steh stored String "hB5JIUfpXZ9yEvhG0nCVUQuKNEqTUhSOmf" maybe not AES encrypted? Because of `hibernatePBEStringEncryptor.setAlgorithm("PBEWITHMD5ANDDES");` 

Which algorithm is more secure?
