### ISSUE TITLE
 jasypt-spring-boot convert bootstrap.yml propertysource to EncryptablePropertySourceWrapper which casued a bug

### ISSUE THREAD

**Issue by henryliu93** [ulisesbocchio/jasypt-spring-boot#296]
**issue:**
jasypt-spring-boot convert bootstrap.yml property source to EncryptablePropertySourceWrapper which caused springboot to fail to load application-${env}.yml property source to environment.

**library version:** 
springboot: 2.3.3.RELEASE
spring cloud: Hoxton.SR8
jasypt-spring-boot-starter: 3.0.4

**here is my config file** 
bootstrap.yml
```
spring:
  profiles:
      active: dev
```

application-dev.yml
```
urls:
  - "https://www.google.com"
```

**phonemonent:**
when i started my application, it seems that spring can not load the properties in application-dev.yml to spring env.

**cause:**
i found that jasypt convert bootstrap property source, which is a OriginTrackedMapPropertySource  , to EncryptablePropertySourceWrapper which was in EncryptablePropertySourceConverter class file.

however, when springboot application start, spring fail to add bootstrap property source to env for jasypt had convert it to 
EncryptablePropertySourceConverter.

//here is part of the spring cloud source code that illustrates why this might happen.
BootstrapApplicationListener.class

```
public void add(PropertySource<?> source) {
		// Only add map property sources added by boot, see gh-476
		if (source instanceof OriginTrackedMapPropertySource
					&& !this.names.contains(source.getName())) {
				this.sources.addPropertySource(source);
				this.names.add(source.getName());
		}
}
```

finally. although i can add 

```
jasypt:
  encryptor:
    skip-property-sources: org.springframework.boot.env.OriginTrackedMapPropertySource
```

to bootstrap.yml to fix it. i hope this issue could be fixed in a later version.

**Comment by zhangyao-zy** [comment]
I have the same problem, but there is no way to use skip-property-sources, because my version is 2.1.1, this version does not seem to have the property

**Comment by zhangyao-zy** [comment]
> 我也有同样的问题，但是没有办法使用skip-property-sources，因为我的版本是2.1.1，这个版本好像没有属性



> I have the same problem, but there is no way to use skip-property-sources, because my version is 2.1.1, this version does not seem to have the property

jasypt.encryptor.bootstrap=false can solve this problem

**Comment by ulisesbocchio** [comment]
@henryliu93 can please validate if this is still happening in 3.0.5 and reopen?

**Comment by bigbugbean** [comment]
I have the same problem.

**Comment by o-o-m** [comment]
![image](https://github.com/ulisesbocchio/jasypt-spring-boot/assets/22236170/bf691450-c92d-46a0-9523-22bec5cfc20e)
still happens

**Comment by o-o-m** [comment]
> ![image](https://user-images.githubusercontent.com/22236170/276875163-bf691450-c92d-46a0-9523-22bec5cfc20e.png) still happens

in 3.0.5
