### ISSUE TITLE
Make lazyJasyptStringEncryptor bean conditional?

### ISSUE THREAD

**Issue by rgala** [ulisesbocchio/jasypt-spring-boot#299]
Maybe a little bit specific scenario, but when I override beans like this

```
jasypt.encryptor.property.resolver-bean=myEncryptablePropertyResolver
jasypt.encryptor.bean=myEncryptor
```

and then I want to inject **myEncryptor** into **myEncryptablePropertyResolver** by using

```
@Autowired
StringEncryptor encryptor
```

it fails because there are two candidates for this bean - **lazyJasyptStringEncryptor** and **myEncryptor** (which impelements **StringEncryptor** interface). The workaround is to explicitly tell Spring I want **myEncryptor** bean injected, but wouldn't it be better to make **lazyJasyptStringEncryptor** conditional on missing bean so there is only one **StringEncryptor** bean in the context? Is the **lazyJasyptStringEncryptor** still needed for something even when it has been overriden?

**Comment by ulisesbocchio** [comment]
Yes, you need to qualify the dependency

**Comment by ulisesbocchio** [comment]
Closing this. There are actually 2 different StringEncryptor beans in the context, the one you provide or is defaulted by the plugin, and an additional one that's the one actually used by the plugin, the lazy one. The lazy is there to bootstrap the encryption context on first decryption of any property so in case you want to turn off encryption, you just don't provide any encrypted properties
