### ISSUE TITLE
springcloud gateway加和jasypt-spring-boot-starter共同使用时会报错

### ISSUE THREAD

**Issue by zqkwcyx** [ulisesbocchio/jasypt-spring-boot#301]
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'authorizationManager': Unsatisfied dependency expressed through field 'iUserApiService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.bairuitech.anychat.feign.service.IUserApiService': FactoryBean threw exception on object creation; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'cachedCompositeRouteLocator' defined in class path resource [org/springframework/cloud/gateway/config/GatewayAutoConfiguration.class]: Unsatisfied dependency expressed through method 'cachedCompositeRouteLocator' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'routeDefinitionRouteLocator' defined in class path resource [org/springframework/cloud/gateway/config/GatewayAutoConfiguration.class]: Unsatisfied dependency expressed through method 'routeDefinitionRouteLocator' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'gatewayProperties' defined in class path resource [org/springframework/cloud/gateway/config/GatewayAutoConfiguration.class]: Initialization of bean failed; nested exception is java.lang.StackOverflowError

jasypt版本
<dependency>
            <groupId>com.github.ulisesbocchio</groupId>
            <artifactId>jasypt-spring-boot-starter</artifactId>
            <version>3.0.4</version>
</dependency>

**Comment by ulisesbocchio** [comment]
3.0.5 is out. Reopen if still an issue

**Comment by wsdszhou** [comment]
这个问题在3.0.5仍然存在

> 3.0.5 is out. Reopen if still an issue

**Comment by wj15118940771** [comment]
spring项目非cloud，当我在配置文件bootstrap.yaml里设置属性jasypt.encryptor.bootstrap: false，不会出现错误
