### ISSUE TITLE
How to disable (tentatively) jasypt?

### ISSUE THREAD

**Issue by hannah23280** [ulisesbocchio/jasypt-spring-boot#307]
Let's say if i want to tentively disable jasypt from decrypting my properties value in my spring-boot based application, what is the cleanest way to do so. Is there any properties key for such purpose

**Comment by ulisesbocchio** [comment]
what would happen to your encrypted properties if you disable it?? In any case, no. But you could easily do it yourself by either using @EnableEncryptableProperties inside a conditional configuration class. Or if you're using the auto-configuration starter by using @EnableAutoConfiguration(exclude=JasyptSpringBootAutoConfiguration.class) inside a conditional configuration class
