### ISSUE TITLE
A small optimization - Jasypt invalidates the springboot custom banner  

### ISSUE THREAD

**Issue by EalenXie** [ulisesbocchio/jasypt-spring-boot#308]
I was using jasypt-spring-boot-starter:3.0.4 when I found out，
My custom SpringBoot Banner is missing  😂。
SpringBoot Version : 2.3.12.RELEASE
It's not a big deal. It's all about getting better。

**Comment by ulisesbocchio** [comment]
that's hilarious.... do me a solid and check with 3.0.5. I tested it myself and worked fine
