### ISSUE TITLE
 When using Binder in BeanDefinitionRegistryPostProcessor, property decryption cannot be performed 

### ISSUE THREAD

**Issue by rwbykit** [ulisesbocchio/jasypt-spring-boot#310]
I found that you convert PropertySource through extension BeanPostProcessor. if I want to use BeanDefinitionRegistryPostProcessor for extension and use Binder for property, binding, the encrypted attributes cannot be decrypted, how can I do?

**Comment by ulisesbocchio** [comment]
You should be able to, so long as you register your post processor after the property sources are converted. Check `JasyptEncryptorConfigurationProperties` source code for reference.

**Comment by SSmale** [comment]
Hi @ulisesbocchio, I am struggling to understand this, would you be able to post an example? [This is an example of the `BeanDefinitionRegistryPostProcessor` I am having trouble with](https://github.com/SSmale/SpringBoot/blob/main/facades/src/main/java/uk/co/iamsimonsmale/facades/DynmicString/autoconfigure/DynamicStringMakerBeanDefinitionRegistrar.java)
