### ISSUE TITLE
Use case of jasypt-spring-boot?

### ISSUE THREAD

**Issue by fapdash** [ulisesbocchio/jasypt-spring-boot#315]
Sorry to ask here but I couldn't figure this out from reading the README.
I found https://github.com/ulisesbocchio/jasypt-spring-boot/issues/93 but the answer didn't completely clear things up for me.

From what I understand the use case for jasypt-spring-boot is to be able to commit secret keys in property files to the VCS.
Similar to [Ansible Vault](https://docs.ansible.com/ansible/2.8/user_guide/vault.html).
Otherwise I could provide the secret keys to the app through environment variables, like it is suggested for the `JASYPT_ENCRYPTOR_PASSWORD`, no?

Is my assessment correct or am I missing something?

**Comment by fapdash** [comment]
Thank you, this helps me.

> The encryption password env var is just one option to provide the secret that decrypts all other secrets.

In https://github.com/ulisesbocchio/jasypt-spring-boot#demo-app you describe passing the password as a system property or as an environment variable. Reading your answer I assume that there are other recommended ways to pass in the password?

**Comment by Oodachi** [comment]
> @ulisesbocchio Thank you, this helps me.
> 
> > The encryption password env var is just one option to provide the secret that decrypts all other secrets.
> 
> In https://github.com/ulisesbocchio/jasypt-spring-boot#demo-app you describe passing the password as a system property or as an environment variable. Reading your answer I assume that there are other recommended ways to pass in the password?

dotenv-java or spring-dotenv
