### ISSUE TITLE
jasypt-spring-boot-starter3.0.3 result in springboot2.3.12  log appear “_IS_UNDEFINED”

### ISSUE THREAD

**Issue by dcqyzb** [ulisesbocchio/jasypt-spring-boot#319]
[crm-gateway:192.168.2.1:9000] 2022-04-17 15:45:19.174 INFO 3376 [-] [background-preinit] o.h.validator.internal.util.Version      : HV000001: Hibernate Validator 6.1.7.Final
[crm-gateway:192.168.2.1:9000] 2022-04-17 15:45:19.904 INFO 3376 [-] [main] ptablePropertiesBeanFactoryPostProcessor : Post-processing PropertySource instances
[crm-gateway:192.168.2.1:9000] 2022-04-17 15:45:19.904 INFO 3376 [-] [main] c.u.j.EncryptablePropertySourceConverter : Skipping PropertySource configurationProperties [class org.springframework.boot.context.properties.source.ConfigurationPropertySourcesPropertySource
[crm-gateway:192.168.2.1:9000] 2022-04-17 15:45:19.914 INFO 3376 [-] [main] c.u.j.EncryptablePropertySourceConverter : Converting PropertySource gateway-properties [org.springframework.core.env.MapPropertySource] to EncryptableMapPropertySourceWrapper
[crm-gateway:192.168.2.1:9000] 2022-04-17 15:45:19.914 INFO 3376 [-] [main] c.u.j.EncryptablePropertySourceConverter : Converting PropertySource bootstrap [org.springframework.core.env.MapPropertySource] to EncryptableMapPropertySourceWrapper
[crm-gateway:192.168.2.1:9000] 2022-04-17 15:45:19.924 INFO 3376 [-] [main] c.u.j.EncryptablePropertySourceConverter : Converting PropertySource systemProperties [org.springframework.core.env.PropertiesPropertySource] to EncryptableMapPropertySourceWrapper
[crm-gateway:192.168.2.1:9000] 2022-04-17 15:45:19.924 INFO 3376 [-] [main] c.u.j.EncryptablePropertySourceConverter : Converting PropertySource systemEnvironment [org.springframework.boot.env.SystemEnvironmentPropertySourceEnvironmentPostProcessor$OriginAwareSystemEnvironmentPropertySource] to EncryptableSystemEnvironmentPropertySourceWrapper
[crm-gateway:192.168.2.1:9000] 2022-04-17 15:45:19.924 INFO 3376 [-] [main] c.u.j.EncryptablePropertySourceConverter : Converting PropertySource random [org.springframework.boot.env.RandomValuePropertySource] to EncryptablePropertySourceWrapper
[crm-gateway:192.168.2.1:9000] 2022-04-17 15:45:19.924 INFO 3376 [-] [main] c.u.j.EncryptablePropertySourceConverter : Converting PropertySource springCloudClientHostInfo [org.springframework.core.env.MapPropertySource] to EncryptableMapPropertySourceWrapper
[crm-gateway:192.168.2.1:9000] 2022-04-17 15:45:19.924 INFO 3376 [-] [main] c.u.j.EncryptablePropertySourceConverter : Converting PropertySource applicationConfig: [classpath:/bootstrap.yml] [org.springframework.boot.env.OriginTrackedMapPropertySource] to EncryptableMapPropertySourceWrapper
[crm-gateway:192.168.2.1:9000] 2022-04-17 15:45:20.144 INFO 3376 [-] [main] c.u.j.filter.DefaultLazyPropertyFilter   : Property Filter custom Bean not found with name 'encryptablePropertyFilter'. Initializing Default Property Filter
[crm-gateway:192.168.2.1:9000] 2022-04-17 15:45:20.154 INFO 3376 [-] [main] c.u.j.r.DefaultLazyPropertyResolver      : Property Resolver custom Bean not found with name 'encryptablePropertyResolver'. Initializing Default Property Resolver
[crm-gateway:192.168.2.1:9000] 2022-04-17 15:45:20.154 INFO 3376 [-] [main] c.u.j.d.DefaultLazyPropertyDetector      : Property Detector custom Bean not found with name 'encryptablePropertyDetector'. Initializing Default Property Detector

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::       (v2.3.12.RELEASE)

[APP_NAME_IS_UNDEFINED:192.168.2.1:0000] 2022-04-17 15:45:22.434 INFO 3376 [-] [main] com.laihu.gateway.GatewayApplication     : The following profiles are active: dev
[APP_NAME_IS_UNDEFINED:192.168.2.1:0000] 2022-04-17 15:45:24.094 WARN 3376 [-] [main] o.s.boot.actuate.endpoint.EndpointId     : Endpoint ID 'service-registry' contains invalid characters, please migrate to a valid format.
[APP_NAME_IS_UNDEFINED:192.168.2.1:0000] 2022-04-17 15:45:24.164 INFO 3376 [-] [main] o.s.cloud.context.scope.GenericScope     : BeanFactory id=43b993c8-07b9-3c63-8554-6d7896454981
[APP_NAME_IS_UNDEFINED:192.168.2.1:0000] 2022-04-17 15:45:24.194 INFO 3376 [-] [main] ptablePropertiesBeanFactoryPostProcessor : Post-processing PropertySource instances
[APP_NAME_IS_UNDEFINED:192.168.2.1:0000] 2022-04-17 15:45:24.194 INFO 3376 [-] [main] c.u.j.EncryptablePropertySourceConverter : Skipping PropertySource configurationProperties [class org.springframework.boot.context.properties.source.ConfigurationPropertySourcesPropertySource
[APP_NAME_IS_UNDEFINED:192.168.2.1:0000] 2022-04-17 15:45:24.194 INFO 3376 [-] [main] c.u.j.EncryptablePropertySourceConverter : Converting PropertySource gateway-properties [org.springframework.core.env.MapPropertySource] to EncryptableMapPropertySourceWrapper
[APP_NAME_IS_UNDEFINED:192.168.2.1:0000] 2022-04-17 15:45:24.194 INFO 3376 [-] [main] c.u.j.EncryptablePropertySourceConverter : Converting PropertySource systemProperties [org.springframework.core.env.PropertiesPropertySource] to EncryptableMapPropertySourceWrapper
[APP_NAME_IS_UNDEFINED:192.168.2.1:0000] 2022-04-17 15:45:24.194 INFO 3376 [-] [main] c.u.j.EncryptablePropertySourceConverter : Converting PropertySource systemEnvironment [org.springframework.boot.env.SystemEnvironmentPropertySourceEnvironmentPostProcessor$OriginAwareSystemEnvironmentPropertySource] to EncryptableSystemEnvironmentPropertySourceWrapper
[APP_NAME_IS_UNDEFINED:192.168.2.1:0000] 2022-04-17 15:45:24.194 INFO 3376 [-] [main] c.u.j.EncryptablePropertySourceConverter : Converting PropertySource random [org.springframework.boot.env.RandomValuePropertySource] to EncryptablePropertySourceWrapper
[APP_NAME_IS_UNDEFINED:192.168.2.1:0000] 2022-04-17 15:45:24.194 INFO 3376 [-] [main] c.u.j.EncryptablePropertySourceConverter : Converting PropertySource springCloudClientHostInfo [org.springframework.core.env.MapPropertySource] to EncryptableMapPropertySourceWrapper
[APP_NAME_IS_UNDEFINED:192.168.2.1:0000] 2022-04-17 15:45:24.194 INFO 3376 [-] [main] c.u.j.EncryptablePropertySourceConverter : Converting PropertySource applicationConfig: [classpath:/application.yml] [org.springframework.boot.env.OriginTrackedMapPropertySource] to EncryptableMapPropertySourceWrapper
[APP_NAME_IS_UNDEFINED:192.168.2.1:0000] 2022-04-17 15:45:24.194 INFO 3376 [-] [main] c.u.j.EncryptablePropertySourceConverter : Converting PropertySource springCloudDefaultProperties [org.springframework.core.env.MapPropertySource] to EncryptableMapPropertySourceWrapper
[APP_NAME_IS_UNDEFINED:192.168.2.1:0000] 2022-04-17 15:45:24.194 INFO 3376 [-] [main] c.u.j.EncryptablePropertySourceConverter : Converting PropertySource cachedrandom [org.springframework.cloud.util.random.CachedRandomPropertySource] to EncryptablePropertySourceWrapper
[APP_NAME_IS_UNDEFINED:192.168.2.1:0000] 2022-04-17 15:45:24.234 INFO 3376 [-] [main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.cloud.client.loadbalancer.reactive.LoadBalancerBeanPostProcessorAutoConfiguration' of type [org.springframework.cloud.client.loadbalancer.reactive.LoadBalancerBeanPostProcessorAutoConfiguration] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
[APP_NAME_IS_UNDEFINED:192.168.2.1:0000] 2022-04-17 15:45:24.234 INFO 3376 [-] [main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.cloud.client.loadbalancer.reactive.LoadBalancerBeanPostProcessorAutoConfiguration$ReactiveLoadBalancerConfig' of type [org.springframework.cloud.client.loadbalancer.reactive.LoadBalancerBeanPostProcessorAutoConfiguration$ReactiveLoadBalancerConfig] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
[APP_NAME_IS_UNDEFINED:192.168.2.1:0000] 2022-04-17 15:45:24.234 INFO 3376 [-] [main] trationDelegate$BeanPostProcessorChecker : Bean 'deferringLoadBalancerExchangeFilterFunction' of type [org.springframework.cloud.client.loadbalancer.reactive.DeferringLoadBalancerExchangeFilterFunction] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
[APP_NAME_IS_UNDEFINED:192.168.2.1:0000] 2022-04-17 15:45:29.774 INFO 3376 [-] [main] o.s.c.g.r.RouteDefinitionRouteLocator    : Loaded RoutePredicateFactory [After]
[APP_NAME_IS_UNDEFINED:192.168.2.1:0000] 2022-04-17 15:45:29.774 INFO 3376 [-] [main] o.s.c.g.r.RouteDefinitionRouteLocator    : Loaded RoutePredicateFactory [Before]
[APP_NAME_IS_UNDEFINED:192.168.2.1:0000] 2022-04-17 15:45:29.774 INFO 3376 [-] [main] o.s.c.g.r.RouteDefinitionRouteLocator    : Loaded RoutePredicateFactory [Between]
[APP_NAME_IS_UNDEFINED:192.168.2.1:0000] 2022-04-17 15:45:29.774 INFO 3376 [-] [main] o.s.c.g.r.RouteDefinitionRouteLocator    : Loaded RoutePredicateFactory [Cookie]
[APP_NAME_IS_UNDEFINED:192.168.2.1:0000] 2022-04-17 15:45:29.784 INFO 3376 [-] [main] o.s.c.g.r.RouteDefinitionRouteLocator    : Loaded RoutePredicateFactory [Header]
[APP_NAME_IS_UNDEFINED:192.168.2.1:0000] 2022-04-17 15:45:29.784 INFO 3376 [-] [main] o.s.c.g.r.RouteDefinitionRouteLocator    : Loaded RoutePredicateFactory [Host]
[APP_NAME_IS_UNDEFINED:192.168.2.1:0000] 2022-04-17 15:45:29.784 INFO 3376 [-] [main] o.s.c.g.r.RouteDefinitionRouteLocator    : Loaded RoutePredicateFactory [Method]
[APP_NAME_IS_UNDEFINED:192.168.2.1:0000] 2022-04-17 15:45:29.784 INFO 3376 [-] [main] o.s.c.g.r.RouteDefinitionRouteLocator    : Loaded RoutePredicateFactory [Path]
[APP_NAME_IS_UNDEFINED:192.168.2.1:0000] 2022-04-17 15:45:29.784 INFO 3376 [-] [main] o.s.c.g.r.RouteDefinitionRouteLocator    : Loaded RoutePredicateFactory [Query]
[APP_NAME_IS_UNDEFINED:192.168.2.1:0000] 2022-04-17 15:45:29.784 INFO 3376 [-] [main] o.s.c.g.r.RouteDefinitionRouteLocator    : Loaded RoutePredicateFactory [ReadBody]
[APP_NAME_IS_UNDEFINED:192.168.2.1:0000] 2022-04-17 15:45:29.784 INFO 3376 [-] [main] o.s.c.g.r.RouteDefinitionRouteLocator    : Loaded RoutePredicateFactory [RemoteAddr]
[APP_NAME_IS_UNDEFINED:192.168.2.1:0000] 2022-04-17 15:45:29.784 INFO 3376 [-] [main] o.s.c.g.r.RouteDefinitionRouteLocator    : Loaded RoutePredicateFactory [Weight]
[APP_NAME_IS_UNDEFINED:192.168.2.1:0000] 2022-04-17 15:45:29.784 INFO 3376 [-] [main] o.s.c.g.r.RouteDefinitionRouteLocator    : Loaded RoutePredicateFactory [CloudFoundryRouteService]
[APP_NAME_IS_UNDEFINED:192.168.2.1:0000] 2022-04-17 15:45:29.834 WARN 3376 [-] [main] c.n.c.sources.URLConfigurationSource     : No URLs will be polled as dynamic configuration sources.
[APP_NAME_IS_UNDEFINED:192.168.2.1:0000] 2022-04-17 15:45:29.834 INFO 3376 [-] [main] c.n.c.sources.URLConfigurationSource     : To enable URLs as dynamic configuration sources, define System property archaius.configurationSource.additionalUrls or make config.properties available on classpath.
[APP_NAME_IS_UNDEFINED:192.168.2.1:0000] 2022-04-17 15:45:29.844 WARN 3376 [-] [main] c.n.c.sources.URLConfigurationSource     : No URLs will be polled as dynamic configuration sources.
[APP_NAME_IS_UNDEFINED:192.168.2.1:0000] 2022-04-17 15:45:29.844 INFO 3376 [-] [main] c.n.c.sources.URLConfigurationSource     : To enable URLs as dynamic configuration sources, define System property archaius.configurationSource.additionalUrls or make config.properties available on classpath.
[APP_NAME_IS_UNDEFINED:192.168.2.1:0000] 2022-04-17 15:45:29.844 INFO 3376 [-] [main] c.u.j.filter.DefaultLazyPropertyFilter   : Property Filter custom Bean not found with name 'encryptablePropertyFilter'. Initializing Default Property Filter
[APP_NAME_IS_UNDEFINED:192.168.2.1:0000] 2022-04-17 15:45:29.854 INFO 3376 [-] [main] c.u.j.r.DefaultLazyPropertyResolver      : Property Resolver custom Bean not found with name 'encryptablePropertyResolver'. Initializing Default Property Resolver
[APP_NAME_IS_UNDEFINED:192.168.2.1:0000] 2022-04-17 15:45:29.854 INFO 3376 [-] [main] c.u.j.d.DefaultLazyPropertyDetector      : Property Detector custom Bean not found with name 'encryptablePropertyDetector'. Initializing Default Property Detector
[APP_NAME_IS_UNDEFINED:192.168.2.1:0000] 2022-04-17 15:45:34.184 INFO 3376 [-] [main] org.reflections.Reflections              : Reflections took 30 ms to scan 1 urls, producing 3 keys and 6 values 
[APP_NAME_IS_UNDEFINED:192.168.2.1:0000] 2022-04-17 15:45:34.214 INFO 3376 [-] [main] org.reflections.Reflections              : Reflections took 20 ms to scan 1 urls, producing 4 keys and 9 values 
[APP_NAME_IS_UNDEFINED:192.168.2.1:0000] 2022-04-17 15:45:34.234 INFO 3376 [-] [main] org.reflections.Reflections              : Reflections took 20 ms to scan 1 urls, producing 3 keys and 10 values 
[APP_NAME_IS_UNDEFINED:192.168.2.1:0000] 2022-04-17 15:45:34.424 INFO 3376 [-] [main] org.reflections.Reflections              : Reflections took 190 ms to scan 171 urls, producing 0 keys and 0 values 
[APP_NAME_IS_UNDEFINED:192.168.2.1:0000] 2022-04-17 15:45:34.454 INFO 3376 [-] [main] org.reflections.Reflections              : Reflections took 30 ms to scan 1 urls, producing 1 keys and 5 values 
[APP_NAME_IS_UNDEFINED:192.168.2.1:0000] 2022-04-17 15:45:34.484 INFO 3376 [-] [main] org.reflections.Reflections              : Reflections took 30 ms to scan 1 urls, producing 1 keys and 7 values 
[APP_NAME_IS_UNDEFINED:192.168.2.1:0000] 2022-04-17 15:45:34.504 INFO 3376 [-] [main] org.reflections.Reflections              : Reflections took 20 ms to scan 1 urls, producing 2 keys and 8 values 
[APP_NAME_IS_UNDEFINED:192.168.2.1:0000] 2022-04-17 15:45:34.664 INFO 3376 [-] [main] org.reflections.Reflections              : Reflections took 160 ms to scan 171 urls, producing 0 keys and 0 values 
[APP_NAME_IS_UNDEFINED:192.168.2.1:0000] 2022-04-17 15:45:40.473 INFO 3376 [-] [main] o.s.b.a.e.web.EndpointLinksResolver      : Exposing 2 endpoint(s) beneath base path '/actuator'
[APP_NAME_IS_UNDEFINED:192.168.2.1:0000] 2022-04-17 15:45:40.603 INFO 3376 [-] [main] o.s.s.c.ThreadPoolTaskScheduler          : Initializing ExecutorService 'Nacos-Watch-Task-Scheduler'
[APP_NAME_IS_UNDEFINED:192.168.2.1:0000] 2022-04-17 15:45:42.984 INFO 3376 [-] [main] o.s.b.web.embedded.netty.NettyWebServer  : Netty started on port(s): 9000
[APP_NAME_IS_UNDEFINED:192.168.2.1:0000] 2022-04-17 15:45:46.874 INFO 3376 [-] [main] c.a.c.n.registry.NacosServiceRegistry    : nacos registry, DEFAULT_GROUP crm-gateway 192.168.2.1:9000 register finished
[APP_NAME_IS_UNDEFINED:192.168.2.1:0000] 2022-04-17 15:45:46.904 INFO 3376 [-] [main] com.laihu.gateway.GatewayApplication     : Started GatewayApplication in 30.719 seconds (JVM running for 33.931)

**Comment by ulisesbocchio** [comment]
new version 3.0.5, reopen if still an issue
