### ISSUE TITLE
jasypt-spring-boot-starter not working with open-jdk 1.8

### ISSUE THREAD

**Issue by kohlideepti** [ulisesbocchio/jasypt-spring-boot#32]
Below is the error I get:
Caused by: java.lang.UnsupportedClassVersionError: com/ulisesbocchio/jasyptspringboot/EnableEncryptablePropertySourcesPostProcessor : Unsupported major.minor version 52.0 (unable to load class com.ulisesbocchio.jasyptspringboot.EnableEncryptablePropertySourcesPostProcessor)
	at org.apache.catalina.loader.WebappClassLoaderBase.findClassInternal(WebappClassLoaderBase.java:2499)
	at org.apache.catalina.loader.WebappClassLoaderBase.findClass(WebappClassLoaderBase.java:859)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1301)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1166)
	at org.springframework.util.ClassUtils.forName(ClassUtils.java:250)
	at org.springframework.boot.SpringApplication.createSpringFactoriesInstances(SpringApplication.java:407)

Execution environment:
openjdk version "1.8.0_91"
OpenJDK Runtime Environment (build 1.8.0_91-8u91-b14-0ubuntu4~15.10.1-b14)
OpenJDK 64-Bit Server VM (build 25.91-b14, mixed mode)

pom.xml contains:
		<dependency>
			<groupId>com.github.ulisesbocchio</groupId>
			<artifactId>jasypt-spring-boot-starter</artifactId>
			<version>1.7</version>
		</dependency>

**Comment by ulisesbocchio** [comment]
Did you try pulling the repo and building from sources with open jdk? 
Do you have public repo I can see your project configuration?

**Comment by ulisesbocchio** [comment]
any update??

**Comment by ulisesbocchio** [comment]
It seems that you're running your app with something else than what you're actually showing. Version 52 is Java 8, so if you get that error it means whatever you're running with doesn't support it, meaning it's a lower version JRE/JDK.

**Comment by kohlideepti** [comment]
Sorry...could not respond earlier.  Yes, I did clone the latest and tried
with java 1.8   Stand alone it works with but when I bundled my project in
war and run inside tomcat, it does not work

tomcat version is 8 and java version installed on ubuntu server is openjdk 8

Regards,
Deepti
Director - gheware.com
+91 - 9740807444

-- Track your phone on Google Map by Google Play App
<https://play.google.com/store/apps/details?id=com.ghewareunigps.android.location.free>
<http://ghewareunigps.in/content/android>

**Comment by ulisesbocchio** [comment]
I see, check what version of java your tomcat is running on, it seems that that's your problem

**Comment by ulisesbocchio** [comment]
Check out this sample project https://github.com/ulisesbocchio/jasypt-spring-boot-samples/tree/master/jasypt-spring-boot-demo-tomcat-ssl which works just fine with Tomcat

**Comment by kohlideepti** [comment]
Checked out this samples project and set the property
-Djasypt-encryptor-password=secret before running and got below when ran in
STS spring boot launch:

Caused by: org.jasypt.exceptions.EncryptionOperationNotPossibleException:
null
at
org.jasypt.encryption.pbe.StandardPBEByteEncryptor.decrypt(StandardPBEByteEncryptor.java:1055)
~[jasypt-1.9.2.jar:na]
at
org.jasypt.encryption.pbe.StandardPBEStringEncryptor.decrypt(StandardPBEStringEncryptor.java:725)
~[jasypt-1.9.2.jar:na]
at
org.jasypt.encryption.pbe.PooledPBEStringEncryptor.decrypt(PooledPBEStringEncryptor.java:498)
~[jasypt-1.9.2.jar:na]
at
com.ulisesbocchio.jasyptspringboot.encryptor.LazyStringEncryptor.decrypt(LazyStringEncryptor.java:32)
~[jasypt-spring-boot-1.8-SNAPSHOT.jar:na]
at
org.jasypt.properties.PropertyValueEncryptionUtils.decrypt(PropertyValueEncryptionUtils.java:72)
~[jasypt-1.9.2.jar:na]
at
com.ulisesbocchio.jasyptspringboot.EncryptablePropertySource.getProperty(EncryptablePropertySource.java:16)
~[jasypt-spring-boot-1.8-SNAPSHOT.jar:na]
at
com.ulisesbocchio.jasyptspringboot.wrapper.EncryptableMapPropertySourceWrapper.getProperty(EncryptableMapPropertySourceWrapper.java:28)
~[jasypt-spring-boot-1.8-SNAPSHOT.jar:na]
at
org.springframework.core.env.PropertySourcesPropertyResolver.getProperty(PropertySourcesPropertyResolver.java:84)
~[spring-core-4.2.4.RELEASE.jar:4.2.4.RELEASE]
at
org.springframework.core.env.PropertySourcesPropertyResolver.getProperty(PropertySourcesPropertyResolver.java:60)
~[spring-core-4.2.4.RELEASE.jar:4.2.4.RELEASE]
at
org.springframework.core.env.AbstractEnvironment.getProperty(AbstractEnvironment.java:531)
~[spring-core-4.2.4.RELEASE.jar:4.2.4.RELEASE]
at
org.springframework.context.support.PropertySourcesPlaceholderConfigurer$1.getProperty(PropertySourcesPlaceholderConfigurer.java:132)
~[spring-context-4.2.4.RELEASE.jar:4.2.4.RELEASE]
at
org.springframework.context.support.PropertySourcesPlaceholderConfigurer$1.getProperty(PropertySourcesPlaceholderConfigurer.java:129)
~[spring-context-4.2.4.RELEASE.jar:4.2.4.RELEASE]
at
org.springframework.core.env.PropertySourcesPropertyResolver.getProperty(PropertySourcesPropertyResolver.java:84)
~[spring-core-4.2.4.RELEASE.jar:4.2.4.RELEASE]
at
org.springframework.core.env.PropertySourcesPropertyResolver.getPropertyAsRawString(PropertySourcesPropertyResolver.java:70)
~[spring-core-4.2.4.RELEASE.jar:4.2.4.RELEASE]
at
org.springframework.core.env.AbstractPropertyResolver$1.resolvePlaceholder(AbstractPropertyResolver.java:207)
~[spring-core-4.2.4.RELEASE.jar:4.2.4.RELEASE]
at
org.springframework.util.PropertyPlaceholderHelper.parseStringValue(PropertyPlaceholderHelper.java:147)
~[spring-core-4.2.4.RELEASE.jar:4.2.4.RELEASE]
at
org.springframework.util.PropertyPlaceholderHelper.replacePlaceholders(PropertyPlaceholderHelper.java:126)
~[spring-core-4.2.4.RELEASE.jar:4.2.4.RELEASE]
at
org.springframework.core.env.AbstractPropertyResolver.doResolvePlaceholders(AbstractPropertyResolver.java:204)
~[spring-core-4.2.4.RELEASE.jar:4.2.4.RELEASE]
at
org.springframework.core.env.AbstractPropertyResolver.resolveRequiredPlaceholders(AbstractPropertyResolver.java:178)
~[spring-core-4.2.4.RELEASE.jar:4.2.4.RELEASE]
at
org.springframework.context.support.PropertySourcesPlaceholderConfigurer$2.resolveStringValue(PropertySourcesPlaceholderConfigurer.java:172)
~[spring-context-4.2.4.RELEASE.jar:4.2.4.RELEASE]
at
org.springframework.beans.factory.support.AbstractBeanFactory.resolveEmbeddedValue(AbstractBeanFactory.java:808)
~[spring-beans-4.2.4.RELEASE.jar:4.2.4.RELEASE]
at
org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1027)
~[spring-beans-4.2.4.RELEASE.jar:4.2.4.RELEASE]
at
org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1014)
~[spring-beans-4.2.4.RELEASE.jar:4.2.4.RELEASE]
at
org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:545)
~[spring-beans-4.2.4.RELEASE.jar:4.2.4.RELEASE]


Regards,
Deepti
Director - gheware.com
+91 - 9740807444

-- Track your phone on Google Map by Google Play App
<https://play.google.com/store/apps/details?id=com.ghewareunigps.android.location.free>
<http://ghewareunigps.in/content/android>

**Comment by ulisesbocchio** [comment]
The passwors is `password`, so you need `-Djasypt-encryptor-password=password` or just uncomment line 31 of `SampleTomcatSslApplication`.
