### ISSUE TITLE
Failed to bind properties under 'spring.datasource.type' to java.lang.Class<javax.sql.DataSource>:

### ISSUE THREAD

**Issue by mrxlh** [ulisesbocchio/jasypt-spring-boot#325]
Description:

Failed to bind properties under 'spring.datasource.type' to java.lang.Class<javax.sql.DataSource>:

    Property: spring.datasource.type
    Value: com.alibaba.druid.pool.DruidDataSource　　
    Origin: class path resource [application-dev.yml] - 4:11
    Reason: failed to convert java.lang.String to java.lang.Class<javax.sql.DataSource> (caused by java.lang.ClassNotFoundException: com.alibaba.druid.pool.DruidDataSource　　)

Action:

Update your application's configuration

使用  springboot 2.x

使用 依赖
<dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>druid-spring-boot-starter</artifactId>
            <version>1.1.13</version>
        </dependency>

**Comment by ulisesbocchio** [comment]
still an issue? would need more details
