### ISSUE TITLE
spring boot jasypt not decrypting property in a config file other than application.yml

### ISSUE THREAD

**Issue by donstrong** [ulisesbocchio/jasypt-spring-boot#33]
Hi Ulises, I created a very simple spring boot REST service (https://github.com/donstrong/spring-boot-jasypt) in attempts to decrypt an encrypted property in a different configuration file (one other than application.yml) and was able to get the value, but it's still encrypted.  When the same encrypted property was added to application.yml, the decrypted value is returned and displayed on the browser.  The config file, application.yml, remains solely within the service's resource folder, but a config. file (under a different name, of course) with encrypted values is stored remotely and accessed by a Spring Cloud Config server.  

Decryption was working fine when @Configuration and @Value annotations were used in the config classes, but when source was changed to use Spring's @EnableConfigurationProperties and @ConfigurationProperties(prefix=... , locations=...), where getters and setters are used in lieu of @Value, the problem arose.  Including @PropertySource and/or @EncryptablePropertySource (with reference to the config file in the classpath) didn't seem to resolve the problem.  At this point, I can revert back to using @Configuration for the class and @Value for each property but thought maybe there was a simple solution when using Spring's @EnableConfigurationProperties and @ConfigurationProperties.  The readme file provides other details.

**Comment by ulisesbocchio** [comment]
Did you check out the sample projects? The scenario you describe is well covered in the examples

**Comment by ulisesbocchio** [comment]
For your `@ConfigurationProperties` annotated class to work with this library you shouldn't use the `locations` property in `@ConfigurationProperties`. Instead ignore that property and import the resource using `@EncryptablePropertySource`.

From your example, change this in `PersonConfig`:
`@ConfigurationProperties(prefix = "com.transamerica.research.spring.boot.jasypt.demo.person", locations = {"classpath:jasypt-demo.yml"})`
To this:
`@ConfigurationProperties(prefix = "com.transamerica.research.spring.boot.jasypt.demo.person")`

And un-comment this in `ApplicationConfig`:
`@PropertySource(name="EncryptedProperties", value = "classpath:jasypt-demo.yml")`

**Comment by donstrong** [comment]
Thanks Ulises.  Unfortunately, after making the recommended changes ...
```
[ PersonConfig.java ]
...
// Notes: 
// - If reading encrypted properties from application.yml, remove locations from @ConfigurationProperties in order for 
//   decryption to work!  Otherwise, the encrypted value is returned.  
// - If reading encrypted properties from jasypt-demo.yml, need to include locations in @ConfigurationProperties in 
//	 order to get the "encrypted" value (but decrypted value still not returned).
@ConfigurationProperties(prefix = "com.transamerica.research.spring.boot.jasypt.demo.person")

@Component
public class PersonConfig {
...
```
```
[ ApplicationConfig.java ]
...
@EnableAutoConfiguration
@EnableConfigurationProperties
@EnableEncryptableProperties
@EncryptablePropertySource(name="EncryptedProperties", value = "classpath:jasypt-demo.yml")

@ComponentScan("com.transamerica.research.spring.boot.jasypt.demo")
public class ApplicationConfig {

}
```
... Spring was unable to retrieve the values for properties defined in jasypt-demo.yml, so the service returned the following ...
```
{
  "username" : null,
  "password" : null
}
```
After applying a number of changes in various ways, the only one that worked (where the decrypted value for password was returned & displayed) was by putting the encrypted properties in ApplicationConfig.yml and removing those same properties in jasypt-demo.yml (in fact, you don't even have to comment out the properties in jasypt-demo.yml as long as they exist in ApplicationConfig.yml).  It's as though Spring is not attempting to look at jasypt-demo.yml if locations is not specified in @ConfigurationProperties.

**Comment by donstrong** [comment]
correction: ApplicationConfig.yml should be application.yml (had ApplicationConfig on my mind)

**Comment by ulisesbocchio** [comment]
check out this sample: https://github.com/ulisesbocchio/jasypt-spring-boot-samples/tree/master/jasypt-spring-boot-demo

It depicts the exact same scenario you're working on

**Comment by ulisesbocchio** [comment]
You're missing a `@Configuration` annotation in your `ApplicationConfig` class. Basically, all the annotations you have in that class are not doing anything without the `@Configuration` annotation.

**Comment by donstrong** [comment]
Still resulted in ...
```
{
  "username" : null,
  "password" : null
}
```
... but expected ...
```
{
  "username" : "grannysmith",
  "password" : "apples4$1"
}
```
Including/Excluding @Configuration in ApplicationConfig and PersonConfig made no difference.  In fact, Spring had no problems retrieving values for properties in jasypt-demo.yml as long as @EnableAutoConfiguration was present and locations = {"classpath:jasypt-demo.yml"} was included in @ConfigurationProperties.  I even placed @EnableAutoConfiguration in the root package (as recommended by Spring docs) but even that may be unnecessary as @SpringBootApplication combines that along with @Configuration and @ComponentScan (http://javabeat.net/enableautoconfiguration-spring-boot/).  

At this point, I'll resign myself to the fact that using @Value is likely the only choice when more than one configuration file exists, such as application.yml and jasypt-demo.yml, and some properties within jasypt-demo.yml are encrypted.  Thanks, again, for taking a look.

**Comment by donstrong** [comment]
I'll take a closer look at https://github.com/ulisesbocchio/jasypt-spring-boot-samples/tree/master/jasypt-spring-boot-demo (because I must be missing something).

**Comment by ulisesbocchio** [comment]
I downloaded your project and tested it with the changes I asked you and it works just fine

**Comment by ulisesbocchio** [comment]
To summarize the changes you need:

change this in `PersonConfig`:
```java
@ConfigurationProperties(prefix = "com.transamerica.research.spring.boot.jasypt.demo.person", locations = {"classpath:jasypt-demo.yml"})
```
To this:
```java
@ConfigurationProperties(prefix = "com.transamerica.research.spring.boot.jasypt.demo.person")
```

And add this to `ApplicationConfig`:
```java
@EncryptablePropertySource(name="EncryptedProperties", value = "classpath:jasypt-demo.properties")
@Configuration
```
Forgot to mention that neither Spring's `@PropertySource` nor `@EncryptablePropertySource` support YAML files. So change your `jasypt-demo.yml` to `jasypt-demo.properties` with this:

```
com.transamerica.research.spring.boot.jasypt.demo.person.username= grannysmith
com.transamerica.research.spring.boot.jasypt.demo.person.password= ENC(0xsGzEjacImaGIEWBZcgEbE4ktUmp+DM)
```

**Comment by donstrong** [comment]
OK, no support for YAML files.  That's interesting because jasypt had no problem decrypting the encrypted properties in several micro services that I've recently built, which all use YAML files.  Those config. classes apply @Value to the properties instead of using Spring's @EnableConfigurationProperties and @ConfigurationProperties, where @Value is essentially replaced by getters & setters.  Swapping out the .yml file with a .properties file worked.  Thanks for your help.

**Comment by donstrong** [comment]
One further note ... when those encrypted properties were present in application.yml, it also worked (without a .properties file).

**Comment by ulisesbocchio** [comment]
Yeah, the limitation is on the @propertySource and @encryptablePropertySource annotations that can't load YAML, the regular application.yml works fine because it doesn't use @PropertySource, it's loaded by Spring Boot itself. If you wanna add another YAML file you'd have to add the appropriate property source in the environment yourself. You can look it up in Spring's documentation.
Please consider starring this repo if you like the library

**Comment by donstrong** [comment]
Thanks Ulises.  I may simply include all encrypted properties in [app-name]-encrypted.[profile].properties for Spring Cloud Config server to read ... that is, should I decide to refactor the config classes to utilize Spring's @EnableConfigurationProperties & @ConfigurationProperties, remove @Value from properties, and add necessary getters & setters (not much effort really).  

btw, starred repo/demo!  Nice work.

**Comment by ulisesbocchio** [comment]
Just FYI, http://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html#boot-features-external-config-yaml-shortcomings. 
I'm gonna look into supporting YAML files in `@EncryptablePropertySource`, seems like a good addition for the library

**Comment by ulisesbocchio** [comment]
Version 1.8 should be in central soon and you'll be able to do this:

```java
@EncryptablePropertySource(name="EncryptedProperties", value = "classpath:jasypt-demo.yml")
```

Enjoy!

**Comment by donstrong** [comment]
Thanks Ulises.
