### ISSUE TITLE
When using version 3.0.3, it will cause: Mongotemplate.find() queries more than 10000 data and loads very slowly

### ISSUE THREAD

**Issue by daimubai** [ulisesbocchio/jasypt-spring-boot#335]
When using version 3.0.3, it will cause: Mongotemplate.find() queries more than 10000 data and loads very slowly。
However, there is no such problem when downgraded to 3.0.2 or upgraded to 3.0.4

**Comment by ulisesbocchio** [comment]
Interesting... Seems resolved in 3.0.4 right? You can try identifying any Pontential changes comparing tags like this:
https://github.com/ulisesbocchio/jasypt-spring-boot/compare/jasypt-spring-boot-parent-3.0.2...jasypt-spring-boot-parent-3.0.3
https://github.com/ulisesbocchio/jasypt-spring-boot/compare/jasypt-spring-boot-parent-3.0.3...jasypt-spring-boot-parent-3.0.4
