### ISSUE TITLE
can't decrypt the configuration file

### ISSUE THREAD

**Issue by nomatterfine** [ulisesbocchio/jasypt-spring-boot#336]
springboot 2.6.3
jasypt-spring-boot-starter 3.0.4  

`spring:
  cloud:
    nacos:
      config:
        server-addr: ENC(DBwqsXOPdoFhuxtMGEiRFBQaDMZTwM4vLZoJdLXhZAE)

jasypt:
  encryptor:
    password: 11111
    algorithm: PBEWithMD5AndDES
`
![image](https://user-images.githubusercontent.com/90117583/189061217-a2569646-201b-45c8-a8b2-e28df7091319.png)

It seems that the yaml is not decrypted when the project starts；

I feel there is no problem with the configuration, add dependencies and increase configuration files

**Comment by zengyr49** [comment]
怎么解决的？
