### ISSUE TITLE
Will there be security issues if I downgrade jasypt-spring-boot-starter from version 3.0.1 to 2.0.0?

### ISSUE THREAD

**Issue by NightHeres** [ulisesbocchio/jasypt-spring-boot#337]
Will there be security issues if I downgrade jasypt-spring-boot-starter from version 3.0.1 to 2.0.0?

**Comment by matthenry87** [comment]
That will be up to you to figure out. Downgrade the version and then use an OSS tool like CheckMarx or similar to determine if any of the dependencies in the dependency tree have CVEs.
