### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by matthenry87** [ulisesbocchio/jasypt-spring-boot#339]
Hi @ulisesbocchio,

I am in the process of upgrading my company's Spring Boot Starters for Spring 6 and Spring Boot 3. I've cloned this repo and relocated the auto-configuration metadata from spring.factories to the new location+filename under src/main/resource/META-INF/spring.

However.. I'm wondering if this repo is being maintained anymore? There are a lot of PRs including a great one that updates one of the test dependencies in order to support Java 16+, but it's just been sitting.

I'm happy to do the work, but if PRs are never going to be reviewed and potentially merged, then we'll create our own small starter equivalent to this one.

Let me know. Thanks!

**Comment by ulisesbocchio** [comment]
Yes, sorry. Been neglecting this a bit if you wanna open a PR for the upgrade I’ll try to merge it soon

**Comment by matthenry87** [comment]
> Yes, sorry. Been neglecting this a bit if you wanna open a PR for the upgrade I’ll try to merge it soon

Great! [Draft PR](https://github.com/ulisesbocchio/jasypt-spring-boot/pull/341) awaiting your preliminary review.

Thanks @ulisesbocchio 👍
