### ISSUE TITLE
Support for SpringBoot 3.0.X

### ISSUE THREAD

**Issue by tomazj** [ulisesbocchio/jasypt-spring-boot#342]
Hi,

Is there a plan to make a new release of this library, which supports integration with Spring Boot 3.0.X?

**Comment by sickan90** [comment]
There is a PR for this https://github.com/ulisesbocchio/jasypt-spring-boot/pull/341. Just need to wait until it is merged and released.

And as I did not want to wait I imported the AutoConfiguration file manually instead:

`
import com.ulisesbocchio.jasyptspringbootstarter.JasyptSpringBootAutoConfiguration;

@SpringBootApplication
@ImportAutoConfiguration(classes = JasyptSpringBootAutoConfiguration.class) // Remove when Jasypt is released for spring boot 3 (or at least 2.7)
public class Application {

    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }

}
`

**Comment by tomazj** [comment]
@sickan90 : Thank you.

**Comment by ulisesbocchio** [comment]
thank you guys! all merged and released on 3.0.5
