### ISSUE TITLE
XML Config file schemas are not available at time of load.

### ISSUE THREAD

**Issue by gorky** [ulisesbocchio/jasypt-spring-boot#36]
Some projects, including ones based on Spring Integration Framework and Spring Batch require XML Files for configuration.  Custom encryption beans are sometimes also required which may need to be defined in XML.  While various XSD Namespaces can be used during loading, the jasypt encryption xsds can not be used by Spring Boot with the Starter plugin.  A Demo project illustrating this has been setup at https://github.com/gorky/jasyptDemo.
This can be run either from command line using ./gradlew run, or in an IDE.

**Comment by ulisesbocchio** [comment]
let me take a quick look at this

**Comment by ulisesbocchio** [comment]
For the namespace to work you just gotta add:
`compile 'org.jasypt:jasypt-spring3:1.9.2'`
to your dependencies. But in any case, you shouldn't mix jasypt-spring-boot and jasypt. Jasypt-spring-boot alone will give you encryptable properties across the entire Spring Environment, regardless of whether or not you have XML configuration, it'll just work. So you don't need to be setting custom encryptors or jasypt config in the XML, just use the properties directly.

**Comment by ulisesbocchio** [comment]
In `DemoMain` you can remove this lines:
```java
@ImportResource({"/jasypt-context.xml"})
@PropertySource("classpath:/application.properties")
```

And add `@SpringBootApplication`.
In `DemoBean`you gotta change:
`@Value("demo.jasypt.value")` for this `@Value("${demo.jasypt.value}")` and after that your app should work. Assuming that you setup the String Encryptor properly, which I couldn't figure out what you were using, but when I replaced `demo.jasypt.value` in your properties for an encrypted value I generated it all worked.
