### ISSUE TITLE
nacos password decryption in application.yml

### ISSUE THREAD

**Issue by sochina-heart** [ulisesbocchio/jasypt-spring-boot#385]
My project uses 3.0.5 jasypt-spring-boot-starter and spring cloud alibaba 2022.0.0.0. After encrypting the nacos password, the nacos configuration cannot be obtained when the project is started. Now the nacos configuration seems to be loaded earlier than jasypt.

**Comment by sochina-heart** [comment]
I just solved this problem, I introduced dependency
`<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-starter-bootstrap</artifactId>
    <version>4.1.0</version>
</dependency>
`The latest springcloud does not seem to support the bootstrap.yml configuration file, so you need to introduce this maven dependency.
`spring:
  config:
    import:`
If this configuration is in the same configuration file as the nacos configuration information, the nacos configuration file will be given priority when the project is started. At this time, jasypt has not yet started to decrypt.
I used the bootstrap.yml configuration file to have a higher priority than application.yml. I put the nacos related configuration into the bootstrap.yml configuration file, and the configuration of the external configuration file introduced by spring into applcation.yml. This problem was successfully solved. At this time, the project At startup, the jasypt configuration file encryption will be loaded first, and then the nacos external configuration will be introduced.

**Comment by sochina-heart** [comment]
My current configuration is as follows：
![a](https://github.com/ulisesbocchio/jasypt-spring-boot/assets/47417868/61621b67-1e96-43e0-82ab-d984893fa189)
![b](https://github.com/ulisesbocchio/jasypt-spring-boot/assets/47417868/54077f79-67d3-4576-b8f1-8feb67788061)

**Comment by zengyr49** [comment]
i  guess you were using spring boot with version lower than 2.4. In spring boot version higher than 2.4, bootstrap file is not supported.
Did you find any other solution?

**Comment by sochina-heart** [comment]
> �i guess you were using spring boot with version lower than 2.4. In spring boot version higher than 2.4, bootstrap file is not supported. Did you find any other solution?

The springboot version I used at the time was 3.0.x, but I forgot the specific version. I didn't find any other solution at the time
