### ISSUE TITLE
SpringBoot3 support

### ISSUE THREAD

**Issue by BeyondTheBlade** [ulisesbocchio/jasypt-spring-boot#399]
spring.factories not allowed in SpringBoot3
can create new artifactId, eg: jasypt-spring-boot3-starter, keep version same too

spring.factories = META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports

please support it, thank you

**Comment by BeyondTheBlade** [comment]
I'm find this code in 3.0.6-SNAPSHOT version . why not upload to maven repo. I just now compile it in local

**Comment by cmadsen** [comment]
+1

**Comment by rpaasche** [comment]
> spring.factories not allowed in SpringBoot3 can create new artifactId, eg: jasypt-spring-boot3-starter, keep version same too
> 
> spring.factories = META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
> 
> please support it, thank you

What's your issue? 3.0.5 works just fine at least with spring boot 3.3.3 and 3.3.4.

**Comment by BeyondTheBlade** [comment]
> > spring.factories not allowed in SpringBoot3 can create new artifactId, eg: jasypt-spring-boot3-starter, keep version same too
> > spring.factories = META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
> > please support it, thank you
> 
> What's your issue? 3.0.5 works just fine at least with spring boot 3.3.3 and 3.3.4.

you are right. I check my code, find it maybe 2.X level up 3.X IDEA Cache question。3.0.5 can used in spring boot 3.3.3
