### ISSUE TITLE
Hi, is it possible to remove "encrypted.property" config, and auto detect "ENC " statement?

### ISSUE THREAD

**Issue by iwaterman** [ulisesbocchio/jasypt-spring-boot#4]
if i want to encrypt the datasource password, now the two configuration below is needed:

spring.datasource.password=ENC(+Nrx10OneKdA9VvXGXkyaxWzNHt+sQ46)
spring.datasource.password.property=

Stand on the common user side, i just feel a little strange, it is possible to use the format
spring.datasource.password.property=+Nrx10OneKdA9VvXGXkyaxWzNHt+sQ46

or 
spring.datasource.password=ENC(+Nrx10OneKdA9VvXGXkyaxWzNHt+sQ46)

if they could be work, it's awesome :)

**Comment by iwaterman** [comment]
sorry, it's my mistake, only the configuration

spring.datasource.password=ENC(+Nrx10OneKdA9VvXGXkyaxWzNHt+sQ46)

is work. sorry again.

jasypt-spring-boot is great!

**Comment by ulisesbocchio** [comment]
Cool, great that it works for you buddy. Let me know if you have any other issues
