### ISSUE TITLE
Updating jasypt-spring-boot to use Spring Boot 1.5.1.RELEASE

### ISSUE THREAD

**Issue by fuzails** [ulisesbocchio/jasypt-spring-boot#43]
Hi 

I am looking to update jasypt-spring-boot to use Spring Boot 1.5.1.RELEASE but I am hitting an issue as per below

```
Error creating bean with name 'beanNamePlaceholderRegistryPostProcessor' defined in class path resource [com/ulisesbocchio/jasyptspringboot/configuration/EncryptablePropertyResolverConfiguration.class]: Unsatisfied dependency expressed through method 'beanNamePlaceholderRegistryPostProcessor' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'transactionRepository': Could not resolve matching constructor (hint: specify index/type/name arguments for simple parameters to avoid type ambiguities)
```

**Comment by ulisesbocchio** [comment]
Yeah, they're not compatible seems like. I'll be upgrading the library in the upcoming days so you can use it with Spring Boot 1.5. For now you're gonna have to stick with Spring Boot 1.4 to use this library. But again, I will be upgrading the library shortly to support the latest version of Spring Boot.
Sorry for the inconvenience

**Comment by ulisesbocchio** [comment]
turns out it was easier than I thought, version 1.12 should be in central soon with compatibility for Spring boot 1.5
