### ISSUE TITLE
Multiple parameters

### ISSUE THREAD

**Issue by prashantjain110** [ulisesbocchio/jasypt-spring-boot#46]
Hi,

I have encrypted user id and password both with different keys, How can I pass the both keys while running the jar.
Ex :
java -Djasypt.encryptor.password=pass1 -Djasypt.encryptor.password=pass2  -jar xxx.jar

I have tried with above command but it is not working.
Please help me to achieve this.

**Comment by ulisesbocchio** [comment]
there's no way out of the box, you'd have to look at creating your custom decryptor

**Comment by ulisesbocchio** [comment]
for instance you can create a custom decryptor that when trying to decrypt something like this:
`secret.property=ENC(key1@nrmZtkF7T0kjG/VodDvBw93Ct8EgjCA+)`
it can parse the encrypted value to figure out it was encrypted with `key1`
