### ISSUE TITLE
passwordEnvName?

### ISSUE THREAD

**Issue by wilemo** [ulisesbocchio/jasypt-spring-boot#47]
application.yml:

jasypt:
    encryptor:
        passwordEnvName:  ${passwordEnvName}

or 

jasypt:
    encryptor:
        password: systemEnvironment[${passwordEnvName}]

I Hope support system Environment password to jasypt-spring-boot.

**Comment by wilemo** [comment]
I did it:
private static final String ENVIRONMENT_VALUE_PREFIX = "systemEnvironment[";
    private static final String ENVIRONMENT_VALUE_SUFFIX = "]";

    @Bean
    public static StringEncryptor stringEncryptor(final Environment environment) {
        PooledPBEStringEncryptor encryptor = new PooledPBEStringEncryptor();
        SimpleStringPBEConfig config = new SimpleStringPBEConfig();
        config.setPassword(**getEnvProperty**(getRequiredProperty(environment, "jasypt.encryptor.password")));
        config.setAlgorithm(getProperty(environment, "jasypt.encryptor.algorithm", "PBEWithMD5AndDES"));
        config.setKeyObtentionIterations(getProperty(environment, "jasypt.encryptor.keyObtentionIterations", "1000"));
        config.setPoolSize(getProperty(environment, "jasypt.encryptor.poolSize", "1"));
        // according Jasypt documentation, if no provider name is explicitly set, the default JVM provider will be used.
        config.setProviderName(getProperty(environment, "jasypt.encryptor.providerName", null));
        config.setSaltGeneratorClassName(getProperty(environment, "jasypt.encryptor.saltGeneratorClassname", "org.jasypt.salt.RandomSaltGenerator"));
        config.setStringOutputType(getProperty(environment, "jasypt.encryptor.stringOutputType", "base64"));
        encryptor.setConfig(config);
        return encryptor;
    }

    private static String getEnvProperty(String value) {
        final String trimmedValue = value.trim();
        if (trimmedValue.startsWith(ENVIRONMENT_VALUE_PREFIX) &&
                trimmedValue.endsWith(ENVIRONMENT_VALUE_SUFFIX)) {
            return System.getenv(value.substring(ENVIRONMENT_VALUE_PREFIX.length(),
                    (value.length() - ENVIRONMENT_VALUE_SUFFIX.length())));
        }
        return value;
    }

**Comment by wilemo** [comment]
org.springframework.context.annotation.ConfigurationClassEnhancer.intercept:350 - @Bean method EnableEncryptablePropertySourcesConfiguration.enableEncryptablePropertySourcesPostProcessor is non-static and returns an object assignable to Spring's BeanFactoryPostProcessor interface. This will result in a failure to process annotations such as @Autowired, @Resource and @PostConstruct within the method's declaring @Configuration class. Add the 'static' modifier to this method to avoid these container lifecycle issues; see @Bean javadoc for complete details.

**Comment by ulisesbocchio** [comment]
The method is in fact static, not sure why spring keeps showing the warning.
