### ISSUE TITLE
jasypt-spring-boot-demo-custom-encryptor does not work if I change to jasypt-spring-boot

### ISSUE THREAD

**Issue by binzou2017** [ulisesbocchio/jasypt-spring-boot#48]
Hi, I tried to change the app to use jasypt-spring-boot instead of starter and added @EnableEncryptableProperties After this it does not pick up the customer encryptor anymore and keep asking for password.

**Comment by ulisesbocchio** [comment]
do you have a sample app I can take a look? Also please check out the samples in the samples repository. There's a variety of small projects that cover all the capabilities and combinations of configurations available.

**Comment by binzou2017** [comment]
Hi, thanks for your reply. I was simply using the sample app CustomEncryptorDemoApplication.java by adding @EnableEncryptableProperties which cause the app to use default encryptor. Later on I was able to get around it by declare the the jasyptStringEncryptor in a class and then import the class before @EnableEncryptableProperties. I think this has something to do with the sequnece of which bean is created.

**Comment by ulisesbocchio** [comment]
It might be, it would be great if you can paste the code here, or point me to a repo where you see the issue so I can troubleshoot it, or if you think this is no longer an issue please let me know so I can close the ticket

**Comment by Chowdaryonpc** [comment]
@binzou2017 @enableencryptableproperties causing  the app to use default encryptor. In the above comment you mentioned that you were able to fix this issue by adding jasyptStringEncryptor  in class and then importing the class before @enableencryptableproperties. Can you please share code example how you did that exactly?

**Comment by ulisesbocchio** [comment]
I was able to reproduce the issue, working on the fix.
For now you can do this to get the same result you should get with `@EnableEncryptableProperties`:
```java
public static void main(String[] args) {
        new SpringApplicationBuilder().sources(CustomEncryptorDemoApplication.class, EnableEncryptablePropertiesConfiguration.class).run(args);
    }
```
Make sure to put the `EnableEncryptablePropertiesConfiguration.class` last in the list of sources.

**Comment by ulisesbocchio** [comment]
I fixed the issue in MASTER, it'll be released soon

**Comment by ulisesbocchio** [comment]
new version 1.13 is out, enjoy

**Comment by binzou2017** [comment]
Thanks ... Bin
