### ISSUE TITLE
How to protect jasypt.encryptor.password in AWS?

### ISSUE THREAD

**Issue by vijayan007** [ulisesbocchio/jasypt-spring-boot#53]
- I am using jasypt-spring-boot to protect the secrets that are stored in application-*properties file in my spring boot app
- Our spring boot app running from AWS and we supply the `jasypt.encryptor.password` via `--jasypt.encryptor.password =value`
-This password can be visible to anyone who can see the history command on that host
- Is there a better way to protect `jasypt.encryptor.password`

**Comment by ulisesbocchio** [comment]
You can install the app as a service with SystemD: https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#deployment-systemd-service

Or you can SET `JAVA_OPTS=-Djasypt.encryptor.password`
Or you can just run `JASYPT_ENCRYPTOR_PASSWORD=password yourApp.jar` and the password won't show. 
Spring will translate any property you define in your environment from `SOME_PROPERTY_NAME` to `some.property.name` (https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-external-config-application-property-files)
