### ISSUE TITLE
no release available

### ISSUE THREAD

**Issue by hohwille** [ulisesbocchio/jasypt-spring-boot#6]
Your solution looks promising and I would like to use it (https://github.com/oasp/oasp4j/issues/279)

Will there be a release available in maven central?
There are not even tags in your git where to build a reliable version from.
Your documentation states that maven will download from the specified dependency but there is no such release. Am I missing something?

**Comment by hohwille** [comment]
BTW: Why dont you provide your work as PR for jasypt?

**Comment by ulisesbocchio** [comment]
I could provide PR for Jasypt, not sure how long it'd take to get it in if you need this right away. I haven't really gotten the time to go through the process of getting the library into maven central. Do you have any experience with it? I've never done it myself. I'll create a release tag with the latest stable version. The documentation says explicitly that the library is not in maven central and that you have to download the code and build it yourself.

**Comment by hohwille** [comment]
> Do you have any experience with it?
Yep:
http://central.sonatype.org/pages/ossrh-guide.html

**Comment by hohwille** [comment]
>  The documentation says explicitly that the library is not in maven central and that you have to download the code and build it yourself. 

Right. Seems that I only read what I expected and wanted to read. Sorry for that.

**Comment by ulisesbocchio** [comment]
no problem man. I'll take a look at the maven central upload process and try to get it there. I've been meaning to, just haven't had the time yet.

**Comment by ulisesbocchio** [comment]
Version 1.2 is in Central now

**Comment by hohwille** [comment]
http://repo1.maven.org/maven2/com/github/ulisesbocchio/jasypt-spring-boot-starter/1.2/
:+1: thanks mate
