### ISSUE TITLE
Tomcat datasource encryption

### ISSUE THREAD

**Issue by ravindardayachand** [ulisesbocchio/jasypt-spring-boot#61]
I have datasource details in tomcat's context.xml which i encrypted using tomcat using steps described below
http://junjun-java.blogspot.in/2017/03/tomcat-datasource-username-password.html but for the step 7 since i use war deployed in tomcat with SpringBootServletInitializer i used the annotation @EnableEncryptableProperties but still the connection is not formed due to encryption please advice

**Comment by ulisesbocchio** [comment]
That example is beyond this library. It creates it's own encryptable datasource and it's initializing it's own 
```java
private StandardPBEStringEncryptor encryptor = new StandardPBEStringEncryptor();
```

You would have to adapt that datasource to use the `Encrytor` bean provided by `jasypt-spring-boot`
