### ISSUE TITLE
Question: Have you tried this with a CloudWatch logging appender?

### ISSUE THREAD

**Issue by curtistee** [ulisesbocchio/jasypt-spring-boot#64]
Hello & thanks for the great work! I'm having difficulties getting an executable Spring Boot jar to run from the CLI (Linux & Mac OSX) when using one of two CloudWatch appenders with LogBack. 
Note I'm using your 4th method with the fluent SpringApplicationBuilder & StandardEncryptableEnvironment approach, and running this with `-Djasypt.encryptor.password={blah}` as an argument.

1. In the first case using the [j256 appender](https://github.com/j256/cloudwatch-logback-appender) I see the following when starting the app:
```bash
18:13:34,608 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [com.j256.cloudwatchlogbackappender.CloudWatchAppender]
18:13:34,610 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [CLOUDWATCH]
18:13:34,610 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [EMERGENCY_FILE] to com.j256.cloudwatchlogbackappender.CloudWatchAppender[CLOUDWATCH]
18:13:34,640 |-INFO in ch.qos.logback.core.hook.DelayingShutdownHook@7e7dec46 - Sleeping for 0 milliseconds
18:13:34,640 |-INFO in ch.qos.logback.core.hook.DelayingShutdownHook@7e7dec46 - Logback context being closed via shutdown hook
```
...and that's as far as it gets, then stops.

2. In the second case using [Pierre David Belanger's appender](https://github.com/pierredavidbelanger/logback-awslogs-appender) I got it to work by writing a custom ApplicationListener which reads the encrypted AWS credentials & sticks them into system properties where the AWS client code can find them.

I prefer the j256 appender personally, as it allows for manually setting the AWS credentials using the `springProperty` tag which your library supports, and has an overflow file appender option.

I created a minimal Spring Boot app which confirms this. Please let me know if you need any more info.

**Comment by ulisesbocchio** [comment]
Do you have the sample code in github for me to take a look?
From the j256 appender docs:

>  You can also set the cloudwatchappender.aws.accessKeyId and cloudwatchappender.aws.secretKey Java System properties which will be used. If neither of those are specified then the appender will use the DefaultAWSCredentialsProviderChain which looks for the access and secret keys in:
> 
> Environment Variables: AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY or AWS_ACCESS_KEY and AWS_SECRET_KEY
> Java System Properties: aws.accessKeyId and aws.secretKey
> Credential file at the default location (~/.aws/credentials) shared by all AWS SDKs and the AWS CLI
> Instance profile credentials delivered through the Amazon EC2 metadata service

You can set your credentials in a few different ways instead of using `logback.xml` although, as you mentioned, jasypt-spring-boot supports encrypted properties in `logback.xml` with the help of spring properties.

```xml
<springProperty name="accessKeyId" source="accessKeyId"/>
<springProperty name="secretKey" source="secretKey"/>
<appender name="CLOUDWATCH" class="com.j256.cloudwatchlogbackappender.CloudWatchAppender">
    ...
    <accessKeyId>${accessKeyId}</accessKeyId>
    <secretKey>${secretKey}</secretKey>
</appender>
```
