### ISSUE TITLE
Loading another jar's spring xml file: properties not decrypted.

### ISSUE THREAD

**Issue by nvp152** [ulisesbocchio/jasypt-spring-boot#76]
I have a spring boot app and I use @EnableEncryptableProperties with the jasypt-spring-boot-starter. It works beautifully for all autowired @Service in my project using @value. However, it does not work for an imported spring xml referencing these properties. The property are uncrypted. This is how I include it:

```
@Configuration
@ImportResource("classpath:beans/client.xml")    //This comes from a maven dependency 
public class ExternalConfig {

}
```
Any ideas of what I may be doing wrong?

**Comment by ulisesbocchio** [comment]
a working example of that working is depicted in the [jasypt-spring-boot-demo](https://github.com/ulisesbocchio/jasypt-spring-boot-samples/blob/master/jasypt-spring-boot-demo/src/main/java/demo/DemoApplication.java) sample.
Please check there in case you're missing something.

**Comment by ulisesbocchio** [comment]
I'd be curious to see the relevant parts of `client.xml` and how is injecting the properties to the declared beans in that config file. Can you share?
