### ISSUE TITLE
Can't get custom string encryptor for bootstrap properties to work

### ISSUE THREAD

**Issue by kheckelmann** [ulisesbocchio/jasypt-spring-boot#77]
Hi,
I'm trying to use jasypt-spring-boot-starter in a spring cloud config project. For most properties it works, but I have a problem with the password for the config server (spring.cloud.config.password) itself. 

It is defined in the bootstrap.yml, so I tried to add the StandardEncryptableEnvironment to the application, as described in the documentation. Now it works if I set the password as system property before, but only if I keep jasypt-spring-boot-starter. According to the documentation, jasypt-spring-boot should be enough if I understand it correctly, but that did not work for me. 

But I would like to use my own encryptor, so I created a jasyptStringEncryptor bean. This bean is found and used during the later steps for all the encrypted passwords that were retrieved from the config server. But for the config server password it creates a new default encryptor in DefaultLazyEncryptor, because he can not find the bean at that time. Is that not possible or am I doing something wrong?

Thank you for your help!

**Comment by ulisesbocchio** [comment]
you can use:
```java
new StandardEncryptableEnvironment(InterceptionMode.WRAPPER, new CustomEncryptor())
```

**Comment by kheckelmann** [comment]
Sorry, I didn't make myself clear. I tried that already - but the custom encryptor is just not used for the password. Instead a new default one is created from EnableEncryptablePropertiesBeanFactoryPostProcessor.postProcessBeanFactory. I think it is created by the default configuration from the jasypt-spring-boot-starter lib, because it doesn't work if I just use jasypt-spring-boot. I'm still not sure, if it is even correct to use the StandardEncryptableEnvironment together with the jasypt-spring-boot-starter lib. Is that the right way to get all passwords (from bootstrap.yml and spring cloud config) decrypted? Or should the StandardEncryptableEnvironment with jasypt-spring-boot be enough?

**Comment by ulisesbocchio** [comment]
let me take a closer look at initialization. Spring cloud uses 2 spring contexts, that might explain why you see the bean initializing twice. One context is private for the initialization of some beans to be able to fetch from the config server and isolate the bootstrap properties from the application properties.

**Comment by ulisesbocchio** [comment]
Are you using the starter jar?

**Comment by kheckelmann** [comment]
I tried both. With the starter lib I get the effect that the default encryptor is used. Without the starter lib and with the StandardEncryptableEnvironment passwords in the bootstrap yml are just not decrypted.

**Comment by ulisesbocchio** [comment]
You have a working sample here: https://github.com/ulisesbocchio/jasypt-spring-boot-samples/tree/master/jasypt-spring-boot-demo-cloud-config
The problem is definitely the fact that cloud-config has its own context, so the encryptable decorators need to be bootstrapped twice, once on each context (the cloud context, and the app context).
The only way to add anything to bootstrap is through the `org.springframework.cloud.bootstrap.BootstrapConfiguration` key in `spring.factories`.
The `jasypt-spring-boot-starter` module adds that configuration. If no using that module, you have to manually add the src/main/resources/META-INF/spring.factories file, and add:
```properties
org.springframework.cloud.bootstrap.BootstrapConfiguration=com.ulisesbocchio.jasyptspringboot.configuration.EnableEncryptablePropertiesConfiguration
```

**Comment by ulisesbocchio** [comment]
You can bootstrap in that key any configuration, for instance, a config class that adds the `@EnableEncryptableProperties` and a custom `StringEncyptor` bean. You would also import that same configuration class from your Application class, in order to have the encryption configuration once.

**Comment by ulisesbocchio** [comment]
how did it go @kheckelmann ?

**Comment by dythebs** [comment]
same problem

**Comment by limng06** [comment]
> You have a working sample here: https://github.com/ulisesbocchio/jasypt-spring-boot-samples/tree/master/jasypt-spring-boot-demo-cloud-config The problem is definitely the fact that cloud-config has its own context, so the encryptable decorators need to be bootstrapped twice, once on each context (the cloud context, and the app context). The only way to add anything to bootstrap is through the `org.springframework.cloud.bootstrap.BootstrapConfiguration` key in `spring.factories`. The `jasypt-spring-boot-starter` module adds that configuration. If not using that module, you have to manually add the src/main/resources/META-INF/spring.factories file, and add:
> 
> ```ini
> org.springframework.cloud.bootstrap.BootstrapConfiguration=com.ulisesbocchio.jasyptspringboot.configuration.EnableEncryptablePropertiesConfiguration
> ```

tks, it works !
