### ISSUE TITLE
version 2.0.0 pom MetaDataParseException

### ISSUE THREAD

**Issue by CodinngLee** [ulisesbocchio/jasypt-spring-boot#78]
compile group: 'com.github.ulisesbocchio', name: 'jasypt-spring-boot', version: '2.0.0'

could not work, the problem:
> Could not resolve com.github.ulisesbocchio:jasypt-spring-boot-starter:2.0.0.
  Required by:
   > Could not resolve com.github.ulisesbocchio:jasypt-spring-boot-starter:2.0.0.
      > Could not parse POM http://maven.aliyun.com/nexus/content/groups/public/com/github/ulisesbocchio/jasypt-spring-boot-starter/2.0.0/jasypt-spring-boot-starter-2.0.0.pom
         > Could not resolve com.github.ulisesbocchio:jasypt-spring-boot-parent:2.0.0.
            > Could not resolve com.github.ulisesbocchio:jasypt-spring-boot-parent:2.0.0.
               > Could not parse POM http://maven.aliyun.com/nexus/content/groups/public/com/github/ulisesbocchio/jasypt-spring-boot-parent/2.0.0/jasypt-spring-boot-parent-2.0.0.pom
                  > Could not find org.springframework.cloud:spring-cloud-dependencies:Finchley.M8.
            > Could not resolve com.github.ulisesbocchio:jasypt-spring-boot-parent:2.0.0.
               > Could not parse POM https://repo.maven.apache.org/maven2/com/github/ulisesbocchio/jasypt-spring-boot-parent/2.0.0/jasypt-spring-boot-parent-2.0.0.pom
                  > Could not find org.springframework.cloud:spring-cloud-dependencies:Finchley.M8

**Comment by ulisesbocchio** [comment]
you need the Finchley.M8 BOM
https://spring.io/blog/2018/03/02/spring-cloud-finchley-m8-is-available

**Comment by bakersemail** [comment]
I had to add spring's repo to my maven config.

**Comment by corporate-gadfly** [comment]
Hate to comment on a closed issue, but in the future, would it be possible to depend on a spring-cloud version that is available in maven central? As, it is, I had to add spring milestone maven repo to my Nexus configuration.
