### ISSUE TITLE
Configuration metadata

### ISSUE THREAD

**Issue by candrews** [ulisesbocchio/jasypt-spring-boot#8]
It would be awesome if jasypt-spring-boot supported configuration metadata http://docs.spring.io/spring-boot/docs/current/reference/html/configuration-metadata.html so documentation and IDE assistance are available for the various properties (jasypt.encryptor.password, jasypt.encryptor.algorithm, etc) which this project supports.

I can imagine this improvement being implemented in 1 of 2 ways:
* Change to use @ConfigurationProperties which, combined with spring-boot-configuration-processor, will generate META-INF/spring-configuration-metadata.json
* Add a manually written META-INF/spring-configuration-metadata.json

**Comment by ulisesbocchio** [comment]
Alright man, I'll take a look. Also, contributions more than welcome :)

**Comment by ulisesbocchio** [comment]
I've added the configuration properties metadata "Automanually". the processor dashes property names with camel  case so I had to edit after generation. Not sure how the IDE will pick up the Javadoc. I haven't release this so if you can checkout the code, build a SNAPSHOT and test that'd be great.
