### ISSUE TITLE
Issue trying to import

### ISSUE THREAD

**Issue by GRRedWings** [ulisesbocchio/jasypt-spring-boot#84]
I'm not sure if this is a library issue, or an issue with the project I'm trying to add it to.

When I add the following dependency to my POM
        <dependency>
            <groupId>com.github.ulisesbocchio</groupId>
            <artifactId>jasypt-spring-boot-starter</artifactId>
            <version>2.0.0</version>
        </dependency>

I get a "Failed to read artifact descriptor" error.  With this I can't import anything from the library.  I was able to download the demo and get those to run. But is there some other dependency I'm missing? Is there a dependency I'm conflicting with?  I'm not sure how to proceed at this point.

**Comment by ulisesbocchio** [comment]
what kind of project is this? Maven? Gradle? May be related to issue #82

**Comment by GRRedWings** [comment]
I am using Maven.  I tried adding the repository snippet you put in my maven file. I'm not sure I'm using it right, but same errors.

**Comment by ulisesbocchio** [comment]
Would you be able to create github repo where I can troubleshoot the issue?

**Comment by GRRedWings** [comment]
I'm not sure I'm able to get a github repo.  I'm going to see if I can't reproduce something similar with your demos.

I will say, that in order to get the Demos to work, I had to edit the parent pom.xml in your demo project.

        <jasypt.spring.boot.version>2.0.1-SNAPSHOT</jasypt.spring.boot.version>

I changed to 
        <jasypt.spring.boot.version>2.0.0</jasypt.spring.boot.version>

**Comment by ulisesbocchio** [comment]
dependencies were fixed in 2.1.0
