### ISSUE TITLE
Not working with webflux and consul-config

### ISSUE THREAD

**Issue by lambav** [ulisesbocchio/jasypt-spring-boot#85]
I have these things in my pom. Its just Hello world using webflux.

	<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-consul-config</artifactId>
			<exclusions>
				<exclusion>
					<groupId>org.springframework.boot</groupId>
					<artifactId>spring-boot-starter-web</artifactId>
				</exclusion>
			</exclusions>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-webflux</artifactId>
			<exclusions>
				<exclusion>
					<groupId>org.springframework.boot</groupId>
					<artifactId>spring-boot-starter-reactor-netty</artifactId>
				</exclusion>
			</exclusions>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-tomcat</artifactId>
		</dependency>

        <dependency>
            <groupId>com.github.ulisesbocchio</groupId>
            <artifactId>jasypt-spring-boot</artifactId>
        </dependency>

        <dependency>
            <groupId>org.bouncycastle</groupId>
            <artifactId>bcprov-jdk15on</artifactId>
        </dependency>

Then I tried to put these properties in spring.factories.
# this is required only for the encrypted values inside the bootstrap.properties
org.springframework.cloud.bootstrap.BootstrapConfiguration=\
com.ulisesbocchio.jasyptspringboot.configuration.EnableEncryptablePropertiesConfiguration

org.springframework.boot.autoconfigure.EnableAutoConfiguration=\
com.ulisesbocchio.jasyptspringboot.configuration.EnableEncryptablePropertiesConfiguration

But i am still getting this exception ( i can see the jar in my classpath) - 

java.security.NoSuchProviderException: no such provider: org.bouncycastle.jce.provider.BouncyCastleProvider

**Comment by ulisesbocchio** [comment]
can you remove:
```

**Comment by ulisesbocchio** [comment]
Closing this for lack of response, but just FYI spring-cloud supports property encryption out of the box
