### ISSUE TITLE
Spring Cloud Compile Reference

### ISSUE THREAD

**Issue by kevindaub** [ulisesbocchio/jasypt-spring-boot#86]
When specifying the package of 'com.github.ulisesbocchio:jasypt-spring-boot:2.0.0', the packages associated to 'org.springframework.cloud:spring-cloud-dependencies'.  I don't believe you need the cloud dependencies when using the non-starter one.

Currently, I get the following stacktrace from gradle. I can force it to resolve, but it's only necessary if you are using spring cloud, so I'm not sure why it's included by default.

Could not resolve all files for configuration ':myproject:compileClasspath'.
> Could not resolve com.github.ulisesbocchio:jasypt-spring-boot:2.0.0.
  Required by:
      project :myproject
   > Could not resolve com.github.ulisesbocchio:jasypt-spring-boot:2.0.0.
      > Could not parse POM com/github/ulisesbocchio/jasypt-spring-boot/2.0.0/jasypt-spring-boot-2.0.0.pom
         > Could not resolve com.github.ulisesbocchio:jasypt-spring-boot-parent:2.0.0.
            > Could not resolve com.github.ulisesbocchio:jasypt-spring-boot-parent:2.0.0.
               > Could not parse POM com/github/ulisesbocchio/jasypt-spring-boot-parent/2.0.0/jasypt-spring-boot-parent-2.0.0.pom
                  > **Could not find org.springframework.cloud:spring-cloud-dependencies:Finchley.M8.**
            > Could not resolve com.github.ulisesbocchio:jasypt-spring-boot-parent:2.0.0.
               > Could not parse POM com/github/ulisesbocchio/jasypt-spring-boot-parent/2.0.0/jasypt-spring-boot-parent-2.0.0.pom
                  > **Could not find org.springframework.cloud:spring-cloud-dependencies:Finchley.M8.**

**Comment by ppsnumi** [comment]
I have same issue.

My internal maven compatible respository could not found jasypt 2.0.0 dependency that can't access milestone repository.

and spring cloud Finchely current status RELEASE not milestone.

**Comment by ulisesbocchio** [comment]
dependencies have been fixed in 2.1.0, sorry for the inconvenience!
