### ISSUE TITLE
Unable to decrypt property when PropertySourcesPlaceholderConfigurer is used

### ISSUE THREAD

**Issue by udaykiran26** [ulisesbocchio/jasypt-spring-boot#9]
My application is using  netflix.archaius component to listen to dynamic changes to properties file. The properties file contains few jasypt encrypted properties. The application uses @EnableEncryptableProperties and required dependencies. 

But encrypted properties are not being  decrypted  when  below class i.e. PropertyResourceConfig is present in the application. Decryption works fine if I remove this class from the application.  I am not sure how to make jasypt decryption working properly along with this class. I think the bean PropertySourcesPlaceholderConfigurer  is causing the problem. 
Please help me to resolve this issue. 

package com.company.control.config;

import java.io.File;
import java.io.IOException;

import org.apache.commons.configuration.Configuration;
import org.apache.commons.lang.StringUtils;
import org.apache.commons.lang.math.NumberUtils;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Profile;
import org.springframework.context.support.PropertySourcesPlaceholderConfigurer;
import org.springframework.core.env.ConfigurableEnvironment;
import org.springframework.core.env.MutablePropertySources;

import com.company.control.dynamicproperties.ApacheCommonsConfigPropertySource;
import com.company.control.dynamicproperties.ConfigurationWatcher;
import com.netflix.config.ConfigurationManager;
import com.netflix.config.DynamicConfiguration;
import com.netflix.config.DynamicURLConfiguration;

@org.springframework.context.annotation.Configuration
@Profile("common") 
public class PropertyResourceConfig {
	@Bean
	public ConfigurationWatcher configurationWatcher() {
		return new ConfigurationWatcher();
	}

	@Bean
	public DynamicConfiguration configuration(ConfigurationWatcher configurationWatcher) throws IOException {
		int pollInterval = NumberUtils.toInt(System.getProperty("config.pollInterval"), 15000);
		String basePath = StringUtils.defaultIfBlank(System.getProperty("config.directory"), "config");
		String appConfigPath = basePath + File.separatorChar + "authorization-control";
		String globalConfig = getFileUrl(appConfigPath, "global.properties");
		String instanceConfig = getFileUrl(appConfigPath, "instance.properties");

		DynamicConfiguration config = new DynamicURLConfiguration( //
				pollInterval, pollInterval, false, //
				globalConfig, instanceConfig);
		config.addConfigurationListener(configurationWatcher);
		ConfigurationManager.install(config);

		return config;
	}

	@Bean
	public PropertySourcesPlaceholderConfigurer propertySourcesPlaceholderConfigurer(ConfigurableEnvironment env,
			Configuration configuration) {
		PropertySourcesPlaceholderConfigurer configurer = new PropertySourcesPlaceholderConfigurer();

		MutablePropertySources sources = new MutablePropertySources();
	    sources.addLast(new ApacheCommonsConfigPropertySource("archaius", configuration));
		configurer.setPropertySources(sources);
		configurer.setEnvironment(env);

		return configurer;
	}

	private static String getFileUrl(String basePath, String filename) {
		String filePath = basePath + File.separatorChar + filename;
		File file = new File(filePath);
		return file.toURI().toString();
	}
}

**Comment by ulisesbocchio** [comment]
Alright buddy. I'll take a look. What version of archaius are you using? I can tell you right now that since you're declaring you're own property sources placeholder configurer that's basically the problem. Try this:
Create a public static method annotated with @Bean that injects ConfigurableEnvironment as argument. Initialize your property source there and add it to the environment using environment.getPropertySources().addLast(yourPropertySource)
That should do the trick since jasypt-spring-boot only decorates property sources present in the environment

**Comment by ulisesbocchio** [comment]
If you really really want to use property place holder configurer there's an encryptable properties placeholder configurer in jasypt-spring-31 for which you don't need jasypt-spring-boot. The purpose of jasypt-spring-boot is to avoid having to declare property placeholder configurers explicitly

**Comment by udaykiran26** [comment]
Hi Ulisesbocchio,

Thanks for looking into the issue. 

Following archaius version has been used in my application. 

com.netflix.archaius:archaius-core:0.7.1

As you suggested , I update the code with EncryptablePropertySourcesPlaceholderConfigurer(encryptor). Here is the updated code. Unfortunately it is not working.  

@Bean(name = "configFileEncryptor")
	@Autowired
    static public StringEncryptor stringEncryptor() {
        PooledPBEStringEncryptor encryptor = new PooledPBEStringEncryptor();
        SimpleStringPBEConfig config = new SimpleStringPBEConfig();
        config.setPassword("company");
        config.setAlgorithm("PBEWithMD5AndDES");
        config.setKeyObtentionIterations("1000");
        config.setPoolSize("1");
        config.setProviderName("SunJCE");
        config.setSaltGeneratorClassName("org.jasypt.salt.RandomSaltGenerator");
        config.setStringOutputType("base64");
        encryptor.setConfig(config);
        return encryptor;
    }
	
	@Bean
	public PropertySourcesPlaceholderConfigurer propertySourcesPlaceholderConfigurer(ConfigurableEnvironment env,
			Configuration configuration, @Qualifier("configFileEncryptor") StringEncryptor encryptor) {
		PropertySourcesPlaceholderConfigurer configurer = new EncryptablePropertySourcesPlaceholderConfigurer(encryptor);

		MutablePropertySources sources = new MutablePropertySources();
	    sources.addLast(new ApacheCommonsConfigPropertySource("archaius", configuration));
		configurer.setPropertySources(sources);
		configurer.setEnvironment(env);

		return configurer;
	}

**Comment by ulisesbocchio** [comment]
Do you have a sample project in github that I can look at?

**Comment by ulisesbocchio** [comment]
Alright buddy, try this:
```
@Bean
public static org.springframework.core.env.PropertySource archaiusPropertySource() throws IOException {
    return new ApacheCommonsConfigPropertySource("archaius", configuration);
}

@Bean
public static PropertySourcesPlaceholderConfigurer propertySourcesPlaceHolderConfigurer(ConfigurableEnvironment environment) throws IOException {
    environment.getPropertySources().addLast(archaiusPropertySource());
    return new PropertySourcesPlaceholderConfigurer();
}
```

There's some weird dependency between ConfigurableEnvironment and the way the default PropertySourcesPlaceholderConfigurer work. Im my sample application, if I just add the property source to the environment the properties are there, but the default PropertySourcesPlaceHolderConfigurer is unable to find the properties. This way both things work.

**Comment by ulisesbocchio** [comment]
You can do this too:
```
public static void main(String[] args) throws IOException {
     new SpringApplicationBuilder(YourApp.class).environment(createEnvironment()).run(args);
}

private static ConfigurableEnvironment createEnvironment() throws IOException {
    ConfigurableEnvironment environment = new StandardEnvironment(); //Or StandardServletEnvironment()
    environment.getPropertySources().addFirst(new ApacheCommonsConfigPropertySource("archaius", getConfiguration()));
    return environment;
  }
```

Basically providing the Environment Object on the spring application builder with your property source already on it

**Comment by ulisesbocchio** [comment]
where you able to figure this out? Do you need any extra help?
I'm closing this issue
