### ISSUE TITLE
Example to store key in a file

### ISSUE THREAD

**Issue by gurpal2000** [ulisesbocchio/jasypt-spring-boot#92]
Hi, can someone point me to an example where the jasypt.encryptor.password can be kept in a file instead. I've tried combinations of @EncryptablePropertySource("file:///d:/password.txt") to no avail.

i see a log line which suggests it works:
Created Encryptable Property Source 'EncryptedPropertySource#1532803802929' from locations: [file:///d:/password.txt]

followed by:
Reason: Required Encryption configuration property missing: jasypt.encryptor.password

using spring boot 2 + jasypt starter

I know a custom reader can be created but is there a simpler/out-of-the-box feature?

thanks

**Comment by sddakoty** [comment]
Provide it as vararg, system property or environment variable. eg:
```-Djasypt.encryptor.password=secretphrase```

**Comment by ulisesbocchio** [comment]
You can technically just include any property file with the property `jasypt.encryptor.password` but it can’t just be a txt file. It has to be properties format if you user @PropertySource. If you use @EncryptablePropertySource it could also be yml
