### ISSUE TITLE
Changing Algorithm fails to decrypt properties.

### ISSUE THREAD

**Issue by ade90036** [ulisesbocchio/jasypt-spring-boot#96]
Hi, 

i have able to reproduce the correct behavious specifying the following:

1. ENV variables containing the TEST=ENC('testfields') to be decrypted by spring boot along with JASYPT_PASSWORD=test

2. spring boot application.property which optionally reads the field is environment variable is not found. This is to have sensible defaults and specify different setting for each environment
decrypted.test=${TEST:7397}
jasypt.encryptor.algorithm=${JASYPT_ALGORITHM:PBEWithMD5AndDES}
jasypt.encryptor.password=${JASYPT_PASSWORD:password}
jasypt.encryptor.keyObtentionIterations=${JASYPT_ITERATIONS:1000}

I manually encrypt the TEST value and when i run the application all is good. Value is decrypted successfully.

If i change the algorithm to something more "exotic", like: PBEWithHmacSHA256AndAES_128, which i specify in my sensible defaults: _application.properties_  like this (and i also update the TEST value to use the encrypted value using the same algorithm)

jasypt.encryptor.algorithm=${JASYPT_ALGORITHM:PBEWithHmacSHA256AndAES_128}

Then the application fails to start as it is unable to decrypt the value. 

to encrypt the value i'm using the snippet of code which is pretty much identical to your DefaultLazyEncryptor. createDefault().

Help!!

**Comment by ade90036** [comment]
Problem is with JASYPT which is not able to wrap the IV property on the string.

A quick test show this behaviour:

```
        def encrypted = encryptor.encrypt("ciao")
        encryptor.decrypt(encrypted); //throws exception
```

The unit test which you have are passing and are also using the same algorithm i'm trying to use, but you are extending the JASYPT to correctly wrap the IV in the ciphertext and then decryptit correctly in **SimplePBEStringEncryptor**

So i'm not really sure why this project is using YASYPT library at all if you need to write our own encrypt / decrypt routines.  

More info on the message = https://sourceforge.net/p/jasypt/bugs/32/

**Comment by ade90036** [comment]
This is the list of possible algorithm defaults.. Unit testing are passing because they are using a class which is not used in the main codebase.. pants..

PBEWITHHMACSHA1ANDAES_128       NOT_POSSIBLE_DECRYPT          
PBEWITHHMACSHA1ANDAES_256       NOT_POSSIBLE                  
PBEWITHHMACSHA224ANDAES_128     NOT_POSSIBLE_DECRYPT          
PBEWITHHMACSHA224ANDAES_256     NOT_POSSIBLE                  
PBEWITHHMACSHA256ANDAES_128     NOT_POSSIBLE_DECRYPT          
PBEWITHHMACSHA256ANDAES_256     NOT_POSSIBLE                  
PBEWITHHMACSHA384ANDAES_128     NOT_POSSIBLE_DECRYPT          
PBEWITHHMACSHA384ANDAES_256     NOT_POSSIBLE                  
PBEWITHHMACSHA512ANDAES_128     NOT_POSSIBLE_DECRYPT          
PBEWITHHMACSHA512ANDAES_256     NOT_POSSIBLE                  
PBEWITHMD5ANDDES                OK                            
PBEWITHMD5ANDTRIPLEDES          NOT_POSSIBLE                  
PBEWITHSHA1ANDDESEDE            OK                            
PBEWITHSHA1ANDRC2_128           OK                            
PBEWITHSHA1ANDRC2_40            OK                            
PBEWITHSHA1ANDRC4_128           OK                            
PBEWITHSHA1ANDRC4_40            OK

**Comment by melloware** [comment]
Your bug definitely explains it all.  The underlying Jasypt libray has not been upgraded since 2014 so it doesn't support the new JDK8 algorithm's.  I worked with this guy to have a fork of Jasypt that supports IV.

https://github.com/alexscal/jasypt

**Comment by ulisesbocchio** [comment]
Hey guys, I’m aware of the shortcomings in fact there’s a string encoder that I threw in somewhere that uses a newer algorithm without jasypt because of the same problem you guys are describing. I’ll take a look at the new fork and and do some tests

**Comment by ade90036** [comment]
If we could create an interface like (org.jasypt.encryption.StringEncryptor) with encrypt and decrypt methods signatures then we could remove Jasypt all together. We could replace the: SimplePBEByteEncryptor with a Java standard JCE implementation which would be enough for majority of users. 

For my production code I use something similar, so I can combine the IV with the encrypted Cipher. 

However I'm still bundling Jasypt library because I need that interface.. StringEncryptor

**Comment by melloware** [comment]
@ade90036 I think its as simple as using that fork and reading this fix I made: https://github.com/alexscal/jasypt/issues/1

It will allow this library to use all old and new encryptions.  If your goal is getting rid of Jasypt that feels like an entirely new Spring Boot Starter should be written since this one is based around Jasypt.  Maybe "Spring Boot Encryption"

**Comment by ade90036** [comment]
Ok that makes perfect sense.. 

I'll consider forking and remove the jasypt myself. I'm not a fan of having a transient dependency in my project which I don't particularly use (except of a interface). One that has not been maintained in ages.

Keep it mind that the JBoss container I'm using has already deployed BouncyCastle as a provided dependency which I'm using quite extensivelly in my project.

Thanks

**Comment by ulisesbocchio** [comment]
@melloware are you releasing the fork to central?

**Comment by melloware** [comment]
@ulisesbocchio Let me see if I can do that.   Jasypt has tons and tons of JARS I might only build and deploy the core Jasypt JAR to Maven Central since that is all your library seems to use.  Any objection to that?
You use:
```xml
            <dependency>
                <groupId>org.jasypt</groupId>
                <artifactId>jasypt</artifactId>
                <version>${jasypt.version}</version>
            </dependency>
```
So I could make a:
```xml
            <dependency>
                <groupId>com.melloware</groupId>
                <artifactId>jasypt</artifactId>
                <version>${jasypt.version}</version>
            </dependency>
```
I feel like Jasypt has had no releases in 5 years so forking it to keep this wonderful Spring Boot accessory alive is worth it.  Do you agree?

**Comment by ulisesbocchio** [comment]
Yes, that would be great @melloware

**Comment by melloware** [comment]
I will submit a PR tonight hopefully.  I have been testing it locally and I am waiting for Maven Central to publish my Jasypt JAR.  Stay tuned.

**Comment by ulisesbocchio** [comment]
Ok great, can you checkout the samples repo and test those too? They all have unit tests. Basically nvm install jasypt spring boot with the new dependency and do a mvn clean install on the root of the samples repo

**Comment by melloware** [comment]
Yep!  didn't know about the samples repo but i will do that as well.

**Comment by melloware** [comment]
OK PR submitted: https://github.com/ulisesbocchio/jasypt-spring-boot/pull/109

And all samples and tests have been updated and everything is working.

**Comment by melloware** [comment]
I just fixed my merge issue I see you updated to add Assymetic.  Its building now.
