### ISSUE TITLE
EncryptablePropertySourceConverter should only convert files defined in .include-sources

### ISSUE THREAD

**Issue by membersound** [ulisesbocchio/jasypt-spring-boot#98]
On startup, I get the following message logged for all of my *.properties:
```
c.u.j.EncryptablePropertySourceConverter : Converting PropertySource applicationConfig: [classpath:/application.properties] [org.springframework.boot.env.OriginTrackedMapPropertySource] to EncryptableMapPropertySourceWrapper
c.u.j.EncryptablePropertySourceConverter : Converting PropertySource applicationConfig: [classpath:/application-custom.properties] [org.springframework.boot.env.OriginTrackedMapPropertySource] to EncryptableMapPropertySourceWrapper
[classpath:/application-custom2.properties] [org.springframework.boot.env.OriginTrackedMapPropertySource] to EncryptableMapPropertySourceWrapper
```

But as I set the following property:
```
jasypt.encryptor.property.filter.include-sources=application.properties
```
It would be great if the ```EncryptablePropertySourceConverter``` could simply skip the files not mentioned there. Because I already told him with the property that the other files don't contain encrypted values, thus these files could be skipped entirely.

**Comment by ulisesbocchio** [comment]
You’re right. I will take a look but I think that all property sources get converted regardless. The filter logic is then applied when properties are looked up, so semantically, it should work as you expect

**Comment by ulisesbocchio** [comment]
closing this since the behavior is as expected. One caveat though, the `include-sources` is based on the property source name, and `application.properties` is not the property source name of the application.properties file, the actual name is `applicationConfig`

**Comment by sddakoty** [comment]
So your advise is to set ```jasypt.encryptor.property.filter.include-sources=applicationConfig```??

**Comment by ulisesbocchio** [comment]
yes, you can either use `include-sources=applicationConfig` or `include-names="some\.property\.prefix\..*"`

**Comment by sddakoty** [comment]
Just as a sidenote: I never got it working with `include-sources` even though I'm only having a simple `application.properties` file, and using `jasypt.encryptor.property.filter.include-sources=applicationConfig`. The password is never decoded.

Inspite, I could get it working with `jasypt.encryptor.property.filter.include-names=spring.datasource..*`

Maybe you could have a look again on the `include-sources` property? This seem not to be working correctly...

**Comment by ulisesbocchio** [comment]
thanks for the heads up, I'll take a look

**Comment by ulisesbocchio** [comment]
should work as expected: https://github.com/ulisesbocchio/jasypt-spring-boot/blob/master/jasypt-spring-boot/src/test/java/com/ulisesbocchio/jasyptspringboot/filter/DefaultPropertyFilterTest.java
